function KMLObj(a,b,c,d){this.title=a;this.description=escape(b);this.marks=[];this.folders=[];this.groundOverlays=[];this.open=c;this.folderid=d}if("undefined"===typeof console||"undefined"===typeof console.log)console={log:function(){}};function Lance$(a){return document.getElementById(a)}var topwin=self,G=google.maps;
function GeoXml(a,b,c,d){this.myvar=a;this.opts=d||{};this.mb=new MessageBox(b,this,"mb",this.opts.messagebox);this.map=b;this.url=c;this.urls="string"==typeof c?[c]:c;this.mb.style=this.opts.messagestyle||{backgroundColor:"silver"};this.alwayspop=this.opts.alwaysinfopop||!1;this.veryquiet=this.opts.veryquiet||!1;this.quiet=this.opts.quiet||!1;this.titlestyle=this.opts.titlestyle||'style = "font-family: arial, sans-serif;font-size: medium;font-weight:bold;"';this.descstyle=this.opts.descstyle||'style = "font-family: arial, sans-serif;font-size: small;padding-bottom:.7em;"';
this.directionstyle=this.opts.directionstyle&&"undefined"!=typeof this.opts.directionstyle?this.opts.directionstyle:'style="font-family: arial, sans-serif;font-size: small;padding-left: 1px;padding-top: 1px;padding-right: 4px;"';this.sidebarfn=this.opts.sidebarfn||GeoXml.addSidebar;this.pointlabelopacity=this.opts.pointlabelopacity||100;this.polylabelopacity=this.opts.polylabelopacity||100;this.hilite=this.opts.hilite||{color:"#aaffff",opacity:0.3,textcolor:"#000000"};this.latestsidebar="";this.forcefoldersopen=
!1;"undefined"!=typeof this.opts.allfoldersopen&&(this.forcefoldersopen=this.opts.allfoldersopen);this.dohilite=!1;"undefined"!=typeof this.opts.dohilite&&!0==this.opts.dohilite&&(this.dohilite=!0);this.clickablepolys=!0;this.zoomHere=15;"number"==typeof this.opts.zoomhere&&(this.zoomHere=this.opts.zoomhere);"boolean"==typeof this.opts.clickablepolys&&(this.clickablepolys=this.opts.clickablepolys);this.clickablemarkers=!0;"boolean"==typeof this.opts.clickablemarkers&&(this.clickablemarkers=this.opts.clickablemarkers);
this.clickablelines=this.opts.singleInfoWindow=!0;"boolean"==typeof this.opts.clickablelines&&(this.clickablelines=this.opts.clickablelines);"undefined"!=typeof this.opts.nolegend&&(this.nolegend=!0);"undefined"==typeof this.opts.preloadHTML&&(this.opts.preloadHTML=!0);this.sidebariconheight=16;"number"==typeof this.opts.sidebariconheight&&(this.sidebariconheight=this.opts.sidebariconheight);this.sidebarsnippet=!1;"boolean"==typeof this.opts.sidebarsnippet&&(this.sidebarsnippet=this.opts.sidebarsnippet);
this.hideall=!1;this.opts.hideall&&(this.hideall=this.opts.hideall);this.opts.markerpane&&"undefined"!=typeof this.opts.markerpane?this.markerpane=this.opts.markerpane:(a=document.createElement("div"),a.style.border="",a.style.position="absolute",a.style.padding="0px",a.style.margin="0px",a.style.fontSize="0px",a.zIndex=1001,this.markerpane=a,this.markerpaneOnMap=!1);b.getDiv().style.fontSize="0px";"undefined"!=typeof proxy&&(this.proxy=proxy);this.proxy||"undefined"==typeof getcapproxy||fixUrlEnd&&
(getcapproxy=fixUrlEnd(getcapproxy));this.publishdirectory="http://www.microimages.com/ogc/tntmap/";topwin=top;try{topname=top.title}catch(f){topwin=self}topwin.publishdirectory&&(this.publishdirectory=topwin.publishdirectory);d.publishdirectory&&(this.publishdirectory=d.publishdirectory);topwin.standalone&&(this.publishdirectory="");this.kmlicon=this.publishdirectory+"images/ge.png";this.docicon=this.publishdirectory+"images/ge.png";this.docclosedicon=this.publishdirectory+"images/geclosed.png";
this.foldericon=this.publishdirectory+"images/folder.png";this.folderclosedicon=this.publishdirectory+"images/folderclosed.png";this.gmlicon=this.publishdirectory+"images/geo.gif";this.rssicon=this.publishdirectory+"images/rssb.png";this.globalicon=this.publishdirectory+"images/geo.gif";this.WMSICON='<img src="'+this.publishdirectory+'images/geo.gif" style="border:none" />';GeoXml.WMSICON=this.WMSICON;this.baseLayers=[];this.bounds=new google.maps.LatLngBounds;this.style={width:2,opacity:0.75,fillopacity:0.4};
this.style.color=this.randomColor();this.style.fillcolor=this.randomColor();this.iwwidth=this.opts.iwwidth||400;this.maxiwwidth=this.opts.maxiwwidth||0;this.iwheight=this.opts.iwheight||0;this.lastMarker={};this.verySmall=1E-7;this.progress=0;this.ZoomFactor=2;this.NumLevels=18;this.maxtitlewidth=0;this.styles=[];this.currdeschead="";this.jsdocs=[];this.jsonmarks=[];this.polyset=[];this.polygons=[];this.polylines=[];this.multibounds=[];this.overlayman=new OverlayManager(b,this);this.overlayman.rowHeight=
20;this.opts.sidebarid&&(this.basesidebar=this.opts.sidebarid);this.kml=[new KMLObj("GeoXML","",!0,0)];this.overlayman.folders.push([]);this.overlayman.subfolders.push([]);this.overlayman.folderhtml.push([]);this.overlayman.folderhtmlast.push(0);this.overlayman.folderBounds.push(new google.maps.LatLngBounds);this.wmscount=0;this.unnamedpath="un-named path";this.unnamedplace="un-named place";this.unnamedarea="un-named area"}
GeoXml.prototype.setOpacity=function(a){this.opts.overrideOpacity=a;for(var b=0;b<this.overlayman.markers.length;b++){var c=this.overlayman.markers[b];c.getPaths?(this.overlayman.markers[b].fillOpacity=a,this.overlayman.markers[b].setOptions({fillOpacity:a})):c.getPath&&(this.overlayman.markers[b].strokeOpacity=a,this.overlayman.markers[b].setOptions({strokeOpacity:a}))}};GeoXml.stripHTML=function(a){return a.replace(/(<([^>]+)>)/ig,"")};
GeoXml.prototype.showIt=function(a,b,c){b="status=yes,resizable=yes,toolbar=0,height="+b+",width="+b+",scrollbars=yes";topwin.widget?(alert(a),this.mb.showMess(a)):(b=window.open("","_blank",b),b.document.open("text/xml"),b.document.write(a),b.document.close())};
GeoXml.prototype.clear=function(a){for(a=0;a<this.overlayman.markers.length;a++)this.overlayman.RemoveMarker(this.overlayman.markers[a]);this.kml=[new KMLObj("GeoXML","",!0,0)];this.maxtitlewidth=0;this.styles=[];this.jsdocs=[];this.jsonmarks=[];this.polyset=[];this.polylines=[];this.multibounds=[];this.bounds=new google.maps.LatLngBounds;this.overlayman=new OverlayManager(this.map,this);this.overlayman.rowHeight=20;"undefined"!=typeof this.basesidebar&&""!=this.basesidebar&&(Lance$(this.basesidebar).innerHTML=
"");this.overlayman.folders.push([]);this.overlayman.subfolders.push([]);this.overlayman.folderhtml.push([]);this.overlayman.folderhtmlast.push(0);this.overlayman.byname=[];this.overlayman.byid=[];this.overlayman.folderBounds.push(new google.maps.LatLngBounds);this.wmscount=0;this.currdeschead=""};
GeoXml.prototype.createMarkerJSON=function(a,b){var c=this.makeIcon(c,a.href),d=new google.maps.LatLng(a.y,a.x);this.overlayman.folderBounds[b].extend(d);this.bounds.extend(d);c.shadow=a.shadow?a.shadow:null;this.opts.createmarker?this.opts.createmarker(d,a.title,unescape(a.description),null,b,c,a.visibility,a.id,a.href,a.snip):this.createMarker(d,a.title,unescape(a.description),null,b,c,a.visibility,a.id,a.href,a.snip)};
GeoXml.prototype.createMarker=function(a,b,c,d,f,e,g,h,k,l){var q=this.myvar,r,s;l=1;e&&e.scale&&(l=e.scale);var n;if(""==k){var m=new GeoXml.Label(a,b,"",this.map,{fontSize:10*l+"px",fontFamily:"Verdana, Arial, Sans-serif"});m.title=b;m.id=h;h={type:"point",title:b,description:b,href:s,shadow:r,visibility:g,x:a.x,y:a.y,id:m.id};this.kml[f].marks.push(h);var D;s="&nbsp;";c="";this.tileset?(D=this.tileset+"$$$"+b+"$$$marker$$$"+n+"$$$"+s+"$$$"+g+"$$$null$$$"+c,m.sidebarid=this.tileset+"sb"+n):(D=this.myvar+
"$$$"+b+"$$$marker$$$"+n+"$$$"+s+"$$$"+g+"$$$null$$$"+c,m.sidebarid=this.myvar+"sb"+n)}else{n=e?e:new google.maps.MarkerImage("http://maps.google.com/mapfiles/kml/pal3/icon40.png",new google.maps.Size(32*l,32*l),new google.maps.Point(0,0),new google.maps.Point(16*l,16*l),new google.maps.Size(32*l,32*l));this.opts.baseicon&&(n.size=this.opts.baseicon.size,n.origin=this.opts.baseicon.orgin,n.anchor=this.opts.baseicon.anchor,l?e&&(n.scaledSize=e.scaledSize):n.scaledSize=this.opts.baseicon.scaledSize,
l=1);l=n;if(this.opts.iconFromDescription){r=RegExp("<\\s*img","ig");var A;l=/src\s*=\s*[\'\"]/;for(e=/[\'\"]/;null!=(A=r.exec(c));){A=c.substr(A.index);var v=l.exec(A);null!=v&&(A=A.substr(v.index+v[0].length),v=e.exec(A),null!=v&&(s=A.substr(0,v.index)))}r=null;s||(s="http://maps.google.com/mapfiles/kml/pal3/icon40.png")}else s="http://maps.google.com/mapfiles/kml/pal3/icon40",null==e||"undefined"==typeof e?(r=s+"s.png",s+=".png",this.opts.baseicon&&(s=this.opts.baseicon.url)):e.url&&(s=e.url);
l=n;l.url=s;e=this.opts.markeroptions||{};"style"==(this.opts.icontype||"style")&&(d=this.styles[d])&&(l=n,l.url=d.url,l.anchor=d.anchor,s=d.url);e.icon=l;d=document.createElement("textarea");d.innerHTML=b;e.title=d.value;if(!l.url.substring(0,4).match(/^http/i)&&"string"==typeof this.url){d=this.url.lastIndexOf("/");var w;-1!=d&&(w=this.url.substring(0,d),d=0);for(;-1!=d&&l.url.match(/^..\//);)d=w.lastIndexOf("/"),l.url=l.url.substring(3),-1!=d&&(w=w.substring(0,d));""!=w&&l.url.match(/^..\//)&&
(w="",l.url=l.url.substring(3));e.icon.url=""==w?l.url:w+"/"+l.url}e.clickable=!0;e.pane=this.markerpane;e.position=a;m=new google.maps.Marker(e);m.title=b;m.id=h;h={type:"point",title:b,description:escape(c),href:s,shadow:r,visibility:g,x:a.x,y:a.y,id:m.id};this.kml[f].marks.push(h);this.opts.pointlabelclass&&(h=new ELabel(a,b,this.opts.pointlabelclass,this.opts.pointlabeloffset,this.pointlabelopacity,!0),m.label=h,h.setMap(this.map));var C,y,I,J;h=this.iwwidth;8*c.length<h&&(h=8*c.length);h<10*
b.length&&(h=10*b.length);this.maxiwwidth&&h>this.maxiwwidth&&(h=this.maxiwwidth);h="<div style = 'width:"+h+"px'><h1 "+this.titlestyle+">"+b+"</h1>";b!=c&&(h+="<div "+this.descstyle+">"+c+"</div>");this.opts.directions?(C=h+"<div "+this.directionstyle+'>Get Directions: <a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click2\');return false;">To Here</a> - <a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click3\');return false;">From Here</a><br><a href="#" onclick="google.maps.event.trigger('+
this.myvar+'.lastMarker,\'click4\');return false;">Search nearby</a> | <a href="#" onclick="'+this.myvar+".map.setCenter(new google.maps.LatLng("+a.lat()+","+a.lng()+"),"+this.zoomHere+');return false;">Zoom Here</a></div>',y=h+"<div "+this.directionstyle+'>Get Directions: To here - <a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click3\');return false;">From Here</a><br>Start address:<form action="http://maps.google.com/maps" method="get" target="_blank"><input type="text" SIZE=35 MAXLENGTH=80 name="saddr" id="saddr" value="" /><INPUT value="Go" TYPE="SUBMIT"><input type="hidden" name="daddr" value="'+
a.lat()+","+a.lng()+"("+b+')"/><br><a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click1\');return false;">&#171; Back</a>| <a href="#" onclick="'+this.myvar+".map.setCenter(new google.maps.LatLng("+a.lat()+","+a.lng()+"),"+this.zoomHere+');return false;">Zoom Here</a></div>',I=h+"<div "+this.directionstyle+'>Get Directions: <a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click2\');return false;">To Here</a> - From Here<br>End address:<form action="http://maps.google.com/maps" method="get"" target="_blank"><input type="text" SIZE=35 MAXLENGTH=80 name="daddr" id="daddr" value="" /><INPUT value="Go" TYPE="SUBMIT"><input type="hidden" name="saddr" value="'+
a.lat()+","+a.lng()+"("+b+')"/><br><a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click1\');return false;">&#171; Back</a> | <a href="#" onclick="'+this.myvar+".map.setCenter(new google.maps.LatLng("+a.lat()+","+a.lng()+"),"+this.zoomHere+');return false;">Zoom Here</a></div>',J=h+"<div "+this.directionstyle+'>Search nearby: e.g. "pizza"<br><form action="http://maps.google.com/maps" method="get"" target="_blank"><input type="text" SIZE=35 MAXLENGTH=80 name="q" id="q" value="" /><INPUT value="Go" TYPE="SUBMIT"><input type="hidden" name="near" value="'+
b+" @"+a.lat()+","+a.lng()+'"/><br><a href="#" onclick="google.maps.event.trigger('+this.myvar+'.lastMarker,\'click1\');return false;">&#171; Back</a> | <a href="#" onclick="'+this.myvar+".map.setCenter(new google.maps.LatLng("+a.lat()+","+a.lng()+"),"+this.zoomHere+');return false;">Zoom Here</a></div>',google.maps.event.addListener(m,"click1",function(){var a={content:C+"</div></div>",pixelOffset:new google.maps.Size(0,2)};this.geoxml.maxiwwidth&&(a.maxWidth=this.geoxml.maxiwwidth);m.infoWindow.setOptions(a)}),
google.maps.event.addListener(m,"click2",function(){var a={content:y+"</div></div>",pixelOffset:new google.maps.Size(0,2)};this.geoxml.maxiwwidth&&(a.maxWidth=this.geoxml.maxiwwidth);m.infoWindow.setOptions(a)}),google.maps.event.addListener(m,"click3",function(){var a={content:I+"</div></div>",pixelOffset:new google.maps.Size(0,2)};this.geoxml.maxiwwidth&&(a.maxWidth=this.geoxml.maxiwwidth);m.infoWindow.setOptions(a)}),google.maps.event.addListener(m,"click4",function(){var a={content:J+"</div></div>",
pixelOffset:new google.maps.Size(0,2)};this.geoxml.maxiwwidth&&(a.maxWidth=this.geoxml.maxiwwidth);m.infoWindow.setOptions(a)})):C=h+"</div>";if(this.opts.markerfollowlinks)k&&"string"==typeof k&&""!=k&&(m.url=k,google.maps.event.addListener(m,"click",function(){window.open(m.url,"_blank");try{eval(q+".lastMarker = m")}catch(a){}}));else if(this.clickablemarkers){var E=this;a={content:C+"</div>",pixelOffset:new google.maps.Size(0,2)};E.maxiwwidth&&(a.maxWidth=E.maxiwwidth);m.infoWindow=new google.maps.InfoWindow(a);
google.maps.event.addListener(m,"click",function(){E.opts.singleInfoWindow&&(E.lastMarker&&E.lastMarker.infoWindow&&E.lastMarker.infoWindow.close(),E.lastMarker=m);m.onMap||E.map.panTo(m.getPosition());this.infoWindow.open(this.map,this)})}this.opts.domouseover&&(m.mess=C+"</div>",m.geoxml=this,google.maps.event.addListener(m,"mouseover",function(a){a||m.getPosition();m.geoxml.mb.showMess(m.mess,5E3)}));this.opts.sidebarid&&(n=this.overlayman.markers.length,s='&nbsp;<img style="vertical-align:text-top;padding:0;margin:0" height="'+
this.sidebariconheight+'" border="0" src="'+s+'">&nbsp;',this.sidebarsnippet?(c=GeoXml.stripHTML(c),c=c.substring(0,40)):c="",D=this.myvar+"$$$"+b+"$$$marker$$$"+n+"$$$"+s+"$$$"+g+"$$$null$$$"+c,m.sidebarid=this.myvar+"sb"+n,m.hilite=this.hilite,m.geoxml=this,m.onOver=function(){if(this.geoxml.dohilite){var a=Lance$(this.sidebarid);a&&"undefined"!=typeof a&&(a.style.backgroundColor=this.hilite.color,a.style.color=this.hilite.textcolor)}},m.onOut=function(){if(this.geoxml.dohilite){var a=Lance$(this.sidebarid);
a&&"undefined"!=typeof a&&(a.style.background="none",a.style.color="")}},google.maps.event.addListener(m,"mouseover",m.onOver),google.maps.event.addListener(m,"mouseout",m.onOut))}this.opts.addmarker?this.opts.addmarker(m,b,f,D,g):this.overlayman.AddMarker(m,b,f,D,g)};
GeoXml.getDescription=function(a){var b="",c=0,d;if("undefined"!=typeof XMLSerializer)for(var f=new XMLSerializer;c<a.childNodes.length;c++)d=f.serializeToString(a.childNodes.item(c)),b+=d;else for(;c<a.childNodes.length;c++)d=a.childNodes.item(c),b+=d.xml;a=b.replace("<![CDATA[","").replace("]]\x3e","");a=a.replace(/\&amp;/g,"&");a=a.replace(/\&lt;/g,"<");a=a.replace(/\&quot;/g,'"');a=a.replace(/\&apos;/g,"'");return a=a.replace(/\&gt;/g,">")};
GeoXml.prototype.processLine=function(a,b,c){var d=this.polylines[a],f=d.lines[b],e,g;if(f){e={points:f,color:d.color,weight:d.width,opacity:d.opacity,type:"line",id:d.id};g=new google.maps.Polyline({map:this.map,path:f,strokeColor:d.color,strokeWeight:d.width,strokeOpactiy:d.opacity});g.bounds=d.pbounds;g.id=d.id;var h=this.overlayman.markers.length;this.polylines[a].lineidx.push(h);var k,l=this.iwwidth,q=d.description;8*q.length<l&&(l=8*q.length);l<12*d.name.length&&(l=12*d.name.length);f="<div style='font-weight: bold; font-size: medium; margin-bottom: 0em;'>"+
d.name;f+="</div><div style='font-family: Arial, sans-serif;font-size: small;width:"+l+"px;'>"+q+"</div>";0==b&&this.opts.sidebarid&&(k='&nbsp;&nbsp;<span style=";border-left:'+d.width+"px solid "+d.color+';">&nbsp;</span> ',this.sidebarsnippet?(q=GeoXml.stripHTML(q),q=q.substring(0,20)):q="",k=this.myvar+"$$$"+d.name+"$$$polyline$$$"+h+"$$$"+k+"$$$"+d.visibility+"$$$"+a+"$$$"+q,this.latestsidebar=this.myvar+"sb"+h);b<d.lines.length&&(setTimeout(this.myvar+".processLine("+a+","+(b+1)+",'"+c+"');",
15),this.opts.sidebarid&&(g.sidebar=this.latestsidebar));this.opts.domouseover&&(g.mess=f);g.title=d.name;g.geoxml=this;g.strokeColor=d.color;g.strokeWeight=d.width;g.strokeOpacity=d.opacity;g.hilite=this.hilite;g.mytitle=g.title;g.map=this.map;g.idx=a;a=g.getPosition();this.clickablelines&&(a={content:f,pixelOffset:new google.maps.Size(0,2),position:a},this.maxiwwidth&&(a.maxWidth=this.maxiwwidth),g.infoWindow=new google.maps.InfoWindow(a));g.onOver=function(){var a=this.geoxml.polylines[this.idx];
if(this.geoxml.dohilite){if(!0!=this.hidden)for(var b=0;b<a.lineidx.length;b++){var c=this.geoxml.overlayman.markers[a.lineidx[b]];c.realColor=c.strokeColor;c.realOpacity=c.strokeOpacity;c.setOptions({strokeColor:this.geoxml.hilite.color,strokeOpacity:this.geoxml.hilite.opacity})}this.sidebar&&(Lance$(this.sidebar).style.backgroundColor=this.hilite.color,Lance$(this.sidebar).style.color=this.hilite.textcolor)}this.mess?this.geoxml.mb.showMess(this.mess,5E3):this.title="Click for more information about "+
this.mytitle};g.onOut=function(){if(this.geoxml.dohilite){var a=this.geoxml.polylines[this.idx];if(!0!=this.hidden)for(var b=0;b<a.lineidx.length;b++)this.geoxml.overlayman.markers[a.lineidx[b]].setOptions({strokeColor:g.realColor,strokeOpacity:g.realOpacity});this.sidebar&&(Lance$(this.sidebar).style.background="none",Lance$(this.sidebar).style.color="")}this.geoxml.mb.hideMess()};google.maps.event.addListener(g,"mouseout",g.onOut);google.maps.event.addListener(g,"mouseover",g.onOver);google.maps.event.addListener(g,
"click",function(a){var b=!1;a?a=a.latLng:(b=!0,a=g.getPosition());if(this.geoxml.clickablelines||b)g.infoWindow.setPosition(a),g.infoWindow.open(this.map)});e.name=d.name;e.description=escape(d.description);this.hideall&&(d.visibility=!1);e.visibility=d.visibility;this.kml[c].marks.push(e);this.overlayman.AddMarker(g,d.name,c,k,d.visibility)}};
GeoXml.prototype.createPolyline=function(a,b,c,d,f,e,g,h,k,l){f={};f.color=b?b:this.randomColor();f.opacity=d?d:0.45;f.width=c?c:4;f.idx=h;f.visibility=k;this.hideall&&(f.visibility=!1);f.name=e;f.description=g;f.lines=a;f.lineidx=[];f.id=l;this.polylines.push(f);setTimeout(this.myvar+".processLine("+(this.polylines.length-1)+",0,'"+h+"');",15)};
GeoXml.prototype.processPLine=function(a,b,c){var d=this.polyset[a],f=d.lines[b];f&&f.length&&d.obj.polylines.push(f);b==d.lines.length-1?this.finishPolygon(d.obj,c):setTimeout(this.myvar+".processPLine("+a+","+(b+1)+",'"+c+"');",5)};GeoXml.prototype.finishPolygon=function(a,b){a.type="polygon";this.finishPolygonJSON(a,b,!1)};
GeoXml.prototype.finishPolygonJSON=function(a,b,c,d){"undefined"==typeof a.visibility&&(a.visibility=!0);this.hideall&&(a.visibility=!1);var f=unescape(a.description);a.opacity=a.fillOpacity;var e={};e.paths=a.polylines;var g="<p style='font-family: Arial, sans-serif; font-weight: bold; font-size: medium; margin-bottom: 0em; margin-top:0em'>"+a.name+"</p>";f!=a.name&&(g+="<div style='font-family: Arial, sans-serif;font-size: small;width:"+this.iwwidth+"px;'>"+f+"</div>");var h=d!="p_"+a.name;this.latestsidebar=
h&&this.opts.sidebarid?this.myvar+"sb"+this.overlayman.markers.length:"";this.opts.domouseover&&(e.mess=g);e.strokeColor=a.strokeColor?a.strokeColor:a.color;a.outline?(e.strokeWeight=a.strokeWeight?a.strokeWeight:a.width,e.strokeOpacity=a.strokeOpacity):(e.strokeWeight=0,e.strokeOpacity=0);e.hilite=this.hilite;e.fillOpacity=a.opacity;e.fillColor=a.color.toString();var k=new google.maps.Polygon(e);k.mb=this.mb;this.domouseover&&(k.mess=g);k.geoxml=this;k.title=a.name;k.id=a.id;d=this.overlayman.markers.length;
h&&(this.multibounds.push(new google.maps.LatLngBounds),this.polygons.push([]));var l=this.multibounds.length-1;this.multibounds[l].extend(k.getBounds().getSouthWest());this.multibounds[l].extend(k.getBounds().getNorthEast());this.polygons[this.polygons.length-1].push(d);k.polyindex=this.polygons.length-1;k.geomindex=l;k.sidebarid=this.latestsidebar;g={content:g,pixelOffset:new google.maps.Size(0,2),position:k.getCenter()};this.maxiwwidth&&(g.maxWidth=this.maxiwwidth);k.infoWindow=new google.maps.InfoWindow(g);
k.onOver=function(){if(this.geoxml.dohilite){if(this.sidebarid){var a=Lance$(this.sidebarid);a&&(a.style.backgroundColor=this.hilite.color,a.style.color=this.hilite.textcolor)}if(this.geoxml.clickablepolys&&(a=this.geoxml.polygons[this.polyindex])&&!0!=this.hidden)for(var b=0;b<a.length;b++){var c=this.geoxml.overlayman.markers[a[b]];c.realColor=e.fillColor;c.realOpacity=e.fillOpacity;c.setOptions({fillColor:this.hilite.color,fillOpacity:this.hilite.opacity})}}this.mess&&k.geoxml.mb.showMess(this.mess,
5E3)};k.onOut=function(){if(this.geoxml.dohilite){if(this.sidebarid){var a=Lance$(this.sidebarid);a&&(a.style.background="none",a.style.color="")}var b;this.geoxml.clickablepolys&&(b=this.geoxml.polygons[this.polyindex]);if(b&&!0!=this.hidden)for(a=0;a<b.length;a++){var c=this.geoxml.overlayman.markers[b[a]];c.setOptions({fillColor:c.realColor.toString(),fillOpacity:c.realOpacity.toString()})}}this.mess&&this.geoxml.mb.hideMess()};k.onClick=function(a){!a&&this.geoxml.alwayspop&&(q=this.geoxml.multibounds[this.geomindex],
this.geoxml.map.fitBounds(q),a={},a.latLng=q.getCenter());a?this.geoxml.clickablepolys&&(this.geoxml.opts.singleInfoWindow&&(this.geoxml.lastMarker&&this.geoxml.lastMarker.infoWindow&&this.geoxml.lastMarker.infoWindow.close(),this.geoxml.lastMarker=this),this.infoWindow.setPosition(a.latLng),this.infoWindow.open(this.geoxml.map)):(this.geoxml.mb.showMess("Zooming to "+k.title,3E3),q=this.geoxml.multibounds[this.geomindex],this.geoxml.map.fitBounds(q))};google.maps.event.addListener(k,"click",k.onClick);
google.maps.event.addListener(k,"mouseout",k.onOut);google.maps.event.addListener(k,"mouseover",k.onOver);a.description=escape(f);this.kml[b].marks.push(a);k.setMap(this.map);var q;this.opts.polylabelclass&&h&&(g=e.getBounds().getCenter(),(l=this.opts.polylabeloffset)||(l=new google.maps.Size(0,0)),l.x=-(6*a.name.length),g=new ELabel(g," "+a.name+" ",this.opts.polylabelclass,l,this.polylabelopacity,!0),k.label=g,g.setMap(this.map));var r;this.basesidebar&&h&&(r='<span style="background-color:'+a.color+
";border:2px solid "+e.strokeColor+';">&nbsp;&nbsp;&nbsp;&nbsp;</span> ',this.sidebarsnippet?(f=GeoXml.stripHTML(f),f=f.substring(0,20)):f="",r=this.myvar+"$$$"+a.name+"$$$polygon$$$"+d+"$$$"+r+"$$$"+a.visibility+"$$$null$$$"+f);c&&(c=k.getBounds().getNorthEast(),f=k.getBounds().getSouthWest(),this.bounds.extend(c),this.bounds.extend(f),this.overlayman.folderBounds[b].extend(f),this.overlayman.folderBounds[b].extend(c));this.overlayman.AddMarker(k,a.name,b,r,a.visibility);return a.name};
GeoXml.prototype.finishLineJSON=function(a,b,c){var d;d=new google.maps.Polyline({path:a.points,strokeColor:a.color,strokeWeight:a.weight,strokeOpacity:a.opacity,clickable:this.clickablelines});d.mytitle=a.name;d.title=a.name;d.strokeColor=a.color;d.strokeOpacity=a.opacity;d.geoxml=this;d.hilite=this.hilite;var f=this.overlayman.markers.length,e=!1;"l_"+a.name!=c?(e=!0,this.polylines.push(a),c=this.polylines.length-1,this.polylines[c].lineidx=[],this.polylines[c].lineidx.push(f),this.latestsidebar=
this.myvar+"sb"+f):(c=this.polylines.length-1,this.polylines[c].lineidx.push(f));this.opts.basesidebar&&(d.sidebarid=this.latestsidebar);d.onOver=function(){if(this.geoxml.dohilite){if(this.sidebarid){var a=Lance$(this.sidebarid);a&&"undefined"!=typeof a&&(a.style.backgroundColor=this.hilite.color)}this.realColor=this.strokeColor;!0!=d.hidden&&d&&"undefined"!=typeof d&&d.setOptions({strokeColor:this.hilite.color})}this.mess?this.geoxml.mb.showMess(this.mess,5E3):this.title="Click for more information about "+
this.mytitle};d.onOut=function(){if(this.geoxml.dohilite){if(this.sidebarid){var a=Lance$(this.sidebarid);a&&"undefined"!=typeof a&&(a.style.background="none")}!0!=d.hidden&&d&&"undefined"!=typeof d&&d.setOptions({strokeColor:this.realColor})}this.mess&&this.geoxml.mb.hideMess()};google.maps.event.addListener(d,"mouseover",d.onOver);google.maps.event.addListener(d,"mouseover",d.onOut);c="";this.kml[b].marks.push(a);var g=unescape(a.description),h=this.iwwidth;8*g.length<h&&(h=8*g.length);h<12*a.name.length&&
(h=12*a.name.length);var k="<div style='font-family: Arial, sans-serif; font-weight: bold; font-size: medium; margin-bottom: 0em;'>"+a.name+"</div>";a.name!=g&&(k+="<div style='font-family: Arial, sans-serif;font-size: small;width:"+h+"px'>"+g+"</div>");d.map=this.map;h={content:k,pixelOffset:new google.maps.Size(0,2),position:point};this.maxiwwidth&&(h.maxWidth=this.maxiwwidth);d.infoWindow=new google.maps.InfoWindow(h);this.clickablelines&&google.maps.event.addListener(d,"click",function(a){a||
d.getPosition();this.infoWindow.open()});this.basesidebar&&e&&(e='&nbsp;&nbsp;<span style=";border-left:'+a.weight+"px solid "+a.color+';">&nbsp;</span> ',"undefined"==typeof a.visibility&&(a.visibility=!0),this.sidebarsnippet?(c=GeoXml.stripHTML(g),c=c.substring(0,20)):c="",c=this.myvar+"$$$"+a.name+"$$$polyline$$$"+f+"$$$"+e+"$$$"+a.visibility+"$$$"+(this.polylines.length-1)+"$$$"+c);f=d.getBounds().getNorthEast();e=d.getBounds().getSouthWest();this.bounds.extend(f);this.bounds.extend(e);this.overlayman.folderBounds[b].extend(e);
this.overlayman.folderBounds[b].extend(f);this.overlayman.AddMarker(d,a.name,b,c,a.visibility);return a.name};
GeoXml.prototype.handlePlaceObj=function(a,b,c,d,f){var e=this.jsonmarks[a],g=e.name;e.title&&(g=e.title);g.length+f>this.maxtitlewidth&&(this.maxtitlewidth=g.length+f);switch(e.type){case "polygon":d="p_"+this.finishPolygonJSON(e,c,!0,d);break;case "line":case "polyline":d="l_"+this.finishLineJSON(e,c,d);break;case "point":this.createMarkerJSON(e,c),d=""}a<b-1?(a=this.myvar+".handlePlaceObj("+(a+1)+","+b+","+c+',"'+d+'",'+f+");",document.status="processing "+g,setTimeout(a,1)):a==this.jsonmarks.length-
1&&(this.progress--,0>=this.progress&&(this.opts.nozoom||this.map.fitBounds(this.bounds),google.maps.event.trigger(this,"parsed"),this.setFolders(),this.opts.sidebarid||(this.mb.showMess("Finished Parsing",1E3),this.ParseURL())))};GeoXml.prototype.parseJSON=function(a,b,c,d,f){this.overlayman.miStart=new Date;this.jsdocs=eval("("+a+")");if(a=Lance$(this.basesidebar))a.style.display="";this.recurseJSON(this.jsdocs[0],b,d,this.basesidebar,0)};
GeoXml.prototype.setFolders=function(){for(var a=this.kml.length,b=0;b<a;b++){var c=this.kml[b].folderid,d=(new String(c)).replace("_folder","FB"),d=Lance$(d),f=Lance$(c);null!==f&&c!=this.opts.sidebarid&&(this.kml[b].open?f.style.display="block":(f.style.display="none",d.src==this.foldericon&&(d.src=this.folderclosedicon),d.src==this.docicon&&(d.src=this.docclosedicon)))}};
GeoXml.prototype.recurseJSON=function(a,b,c,d,f){var e=a.marks,g=a.title;d||(d=0);var h=unescape(a.description);!h&&c&&(h=c);c=this.forcefoldersopen;a.open&&(c=!0);var k=!0;"undefined"!=typeof a.visibility&&a.visibility&&(k=!0);this.hideall&&(k=!1);var l=a.snippet,q=this.overlayman.folders.length;h||(h=g);this.overlayman.folders.push([]);this.overlayman.subfolders.push([]);this.overlayman.folderhtml.push([]);this.overlayman.folderhtmlast.push(0);this.overlayman.folderBounds.push(new google.maps.LatLngBounds);
this.kml.push(new KMLObj(b,h,c));if(!f&&a.folders&&1<a.folders.length||a.marks.length)b=2>f||1>a.marks.length?this.globalicon:this.foldericon,d=this.createFolder(q,g,d,b,h,l,c,k);g=this.jsonmarks.length;h=g+e.length;for(b=0;b<e.length;b++)c=e[b],this.jsonmarks.push(c),c=unescape(c.description),this.opts.preloadHTML&&c&&c.match(/<(\s)*img/i)&&(k=document.createElement("span"),k.style.visibility="visible",k.style.position="absolute",k.style.left="-1200px",k.style.top="-1200px",k.style.zIndex=this.overlayman.markers.length,
document.body.appendChild(k),k.innerHTML=c);e.length&&this.handlePlaceObj(g,h,q,null,f);h=c=0;if("undefined"!=typeof a.folders)for(c=a.folders.lenth,g=0;g<a.folders.length;++g)h=this.jsdocs[a.folders[g]],h=this.recurseJSON(h,h.title,h.description,d,f+1),this.overlayman.subfolders[q].push(h),this.overlayman.folderBounds[q].extend(this.overlayman.folderBounds[h].getSouthWest()),this.overlayman.folderBounds[q].extend(this.overlayman.folderBounds[h].getNorthEast()),h!=q&&this.kml[q].folders.push(h);if(c||
e.length)this.bounds.extend(this.overlayman.folderBounds[q].getSouthWest()),this.bounds.extend(this.overlayman.folderBounds[q].getNorthEast());return q};
GeoXml.prototype.createPolygon=function(a,b,c,d,f,e,g,h,k,l,q,r,s,n){var m={};m.obj={description:k,name:h};m.obj.polylines=[];m.obj.id=n;m.obj.visibility=q;m.obj.fill=r;m.obj.outline=s;m.fillcolor=f;m.obj.strokecolor=b;m.strokeOpacity=d;m.strokeColor=b?b:this.style.color;m.obj.color=f?f:this.randomColor();d?m.obj.opacity=d:(m.obj.opacity=this.style.opacity,m.strokeOpacity=this.style.opacity);m.obj.fillOpacity=e?e:this.style.fillopacity;m.strokeWeight=c?c:this.style.width;m.bounds=g;m.lines=a;m.sidebarid=
this.opts.sidebarid;this.polyset.push(m);setTimeout(this.myvar+".processPLine("+(this.polyset.length-1)+",0,'"+l+"')",1)};
GeoXml.prototype.toggleFolder=function(a){var b=Lance$(this.myvar+"_folder"+a),c=Lance$(this.myvar+"TB"+a);a=Lance$(this.myvar+"FB"+a);"none"==b.style.display?(b.style.display="",c&&(c.style.fontWeight="normal"),a.src==this.folderclosedicon&&(a.src=this.foldericon),a.src==this.docclosedicon&&(a.src=this.docicon)):(b.style.display="none",c&&(c.style.fontWeight="bold"),a.src==this.foldericon&&(a.src=this.folderclosedicon),a.src==this.docicon&&(a.src=this.docclosedicon))};
GeoXml.prototype.saveJSON=function(){if(topwin.standalone){var a=browseForSave("Select a directory to place your json file","JSON Data Files (*.js)|*.js|All Files (*.*)|*.*","JSON-DATA");if("undefined"!=typeof a){var b=JSON.stringify(this.kml);saveLocalFile(a+".js",b)}}else"undefined"!=typeof JSON?(b=JSON.stringify(this.kml),"undefined"!=typeof serverBlessJSON?serverBlessJSON(escape(b),"MyKJSON"):this.showIt(b)):console?console.error("No JSON methods currently available"):alert("No JSON methods currently available")};
GeoXml.prototype.hide=function(){this.contentToggle(1,!1);this.overlayman.currentZoomLevel=-1;OverlayManager.Display(this.overlayman)};GeoXml.prototype.setMap=function(a){a?this.show():this.hide()};GeoXml.prototype.show=function(){this.contentToggle(1,!0);this.overlayman.currentZoomLevel=-1;OverlayManager.Display(this.overlayman)};GeoXml.prototype.toggleContents=function(a,b){this.contentToggle(a,b);this.overlayman.currentZoomLevel=-1;OverlayManager.Display(this.overlayman)};
GeoXml.prototype.contentToggle=function(a,b){var c=this.overlayman.folders[a],d,f;if("undefined"==typeof c)this.mb.showMess("folder "+c+" not defined");else{if(b)for(f=0;f<c.length;f++)this.overlayman.markers[c[f]].setMap(this.map),this.overlayman.markers[c[f]].onMap=!0,this.basesidebar&&(d=Lance$(this.myvar+""+c[f]+"CB"))&&"undefined"!=typeof d&&(d.checked=!0),this.overlayman.markers[c[f]].hidden=!1;else for(f=0;f<c.length;f++)this.overlayman.markers[c[f]].hidden=!0,this.overlayman.markers[c[f]].onMap=
!1,this.overlayman.markers[c[f]].setMap(null),this.basesidebar&&(d=Lance$(this.myvar+""+c[f]+"CB"))&&"undefined"!=typeof d&&(d.checked=!1);c=this.overlayman.subfolders[a];if("undefined"!=typeof c)for(f=0;f<c.length;f++)c[f]!=a&&(this.basesidebar&&(d=Lance$(this.myvar+""+c[f]+"FCB"))&&"undefined"!=typeof d&&(d.checked=!!b),this.contentToggle(c[f],b))}};
GeoXml.prototype.showHide=function(a,b,c){if(null!==a)b?(this.overlayman.markers[a].setMap(this.map),this.overlayman.markers[a].onMap=!0,this.overlayman.markers[a].hidden=!1):(this.overlayman.markers[a].setMap(null),this.overlayman.markers[a].onMap=!1,this.overlayman.markers[a].hidden=!0);else if(a=this.polylines[c],b)for(b=0;b<a.lineidx.length;b++)this.overlayman.markers[a.lineidx[b]].setMap(this.map),this.overlayman.markers[a.lineidx[b]].onMap=!0,this.overlayman.markers[a.lineidx[b]].hidden=!1;
else for(b=0;b<a.lineidx.length;b++)this.overlayman.markers[a.lineidx[b]].setMap(null),this.overlayman.markers[a.lineidx[b]].onMap=!1,this.overlayman.markers[a.lineidx[b]].hidden=!0;this.overlayman.currentZoomLevel=-1;OverlayManager.Display(this.overlayman,!0)};
GeoXml.prototype.toggleOff=function(a,b){b?(this.overlayman.markers[a].setMap(this.map),this.overlayman.markers[a].hidden=!1):(this.overlayman.markers[a].setMap(null),this.overlayman.markers[a].hidden=!0);this.labels.onMap&&(this.labels.setMap(null),this.labels.setMap(this.map))};
GeoXml.addSidebar=function(a,b,c,d,f,e,g,h){var k="checked";"false"==e&&(k="");e="";var l=a+"sb"+d;h=h&&"undefined"!=h?"<br><span class='"+a+"snip'>"+h+"</span>":"";switch(c){case "marker":e='<li id="'+l+'" onmouseout="google.maps.event.trigger('+a+".overlayman.markers["+d+"],'mouseout');\" onmouseover=\"google.maps.event.trigger("+a+".overlayman.markers["+d+"],'mouseover');\" ><input id=\""+a+""+d+'CB" type="checkbox" style="vertical-align:middle" '+k+' onclick="'+a+".showHide("+d+',this.checked)"><a href="#" onclick="google.maps.event.trigger('+
a+".overlayman.markers["+d+"],'click');return false;\">"+f+b+"</a>"+h+"</li>";break;case "polyline":e='<li id="'+l+'"  onmouseout="'+a+".overlayman.markers["+d+'].onOut();" onmouseover="'+a+".overlayman.markers["+d+'].onOver();" ><input id="'+a+""+d+'CB" type="checkbox" '+k+' onclick="'+a+".showHide(null,this.checked,"+g+')"><span style="margin-top:6px;"><a href="#" onclick="google.maps.event.trigger('+a+".overlayman.markers["+d+"],'click');return false;\">&nbsp;"+f+b+"</a></span>"+h+"</li>";break;
case "polygon":e='<li id="'+l+'"  onmouseout="'+a+".overlayman.markers["+d+'].onOut();" onmouseover="'+a+".overlayman.markers["+d+'].onOver();" ><input id="'+a+""+d+'CB" type="checkbox" '+k+' onclick="'+a+".showHide("+d+',this.checked)"><span style="margin-top:6px;"><a href="#" onclick="google.maps.event.trigger('+a+".overlayman.markers["+d+"],'click');return false;\">&nbsp;"+f+b+"</a></span></nobr>"+h+"</li>";break;case "groundoverlay":e='<li id="'+l+'"><input id="'+a+""+d+'CB" type="checkbox" '+
k+' onclick="'+a+".showHide("+d+',this.checked)"><span style="margin-top:6px;"><a href="#" onclick="google.maps.event.trigger('+a+".overlayman.markers["+d+"],'zoomto');return false;\">&nbsp;"+f+b+"</a></span>"+h+"</li>";break;case "tiledoverlay":e='<li id="'+l+'"><nobr><input id="'+a+""+d+'CB" type="checkbox" '+k+' onclick="'+a+".toggleOff("+d+',this.checked)"><span style="margin-top:6px;"><a href="#" oncontextMenu="'+a+".upgradeLayer("+g+');return false;" onclick="google.maps.event.trigger('+a+".overlayman.markers["+
d+"],'zoomto');return false;\">"+GeoXml.WMSICON+"&nbsp;"+b+"</a><br />"+f+"</span>"+h+"</li>"}return e};GeoXml.addDropdown=function(a,b,c,d,f){return'<option value="'+d+'">'+b+"</option>"};
GeoXml.prototype.parse=function(a){var b=[];"undefined"!=typeof a&&(b="string"!=typeof a?a:a.split(","));this.progress+=this.urls.length;for(a=0;a<this.urls.length;a++){var c=b[a];"undefined"!=typeof c&&c&&"null"!=c||(c=this.urls[a].split("/"),c=c[c.length-1]);this.mb.showMess("Loading "+c);-1!=this.urls[a].search(/\.js$/i)?this.loadJSONUrl(this.urls[a],c):this.loadXMLUrl(this.urls[a],c)}};
GeoXml.prototype.removeAll=function(){this.allRemoved=!0;for(var a=0;a<this.overlayman.markers.length;a++)this.toggleOff(a,!1)};GeoXml.prototype.addAll=function(){this.allRemoved=!1;for(var a=0;a<this.overlayman.markers.length;a++)this.toggleOff(a,!0)};
GeoXml.prototype.processString=function(a,b,c){var d=[];b&&(d=b.split(","));this.docs="string"==typeof a?[a]:a;this.progress+=this.docs.length;for(a=0;a<this.docs.length;a++)this.mb.showMess("Processing "+d[a]),this.processing(this.parseXML(this.docs[a]),d[a],c)};
GeoXml.prototype.parseXML=function(a){var b,c;try{window.DOMParser?(c=new DOMParser,b=c.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(d){b=void 0}b&&b.documentElement&&!b.getElementsByTagName("parsererror").length||(a="Invalid XML: "+a,console?console.error(a):alert(a));return b};
GeoXml.prototype.getText=function(a){var b="",c;if(!a||!a.childNodes)return b;a=a.childNodes;for(var d=0;a[d];d++)c=a[d],3===c.nodeType||4===c.nodeType?b+=c.nodeValue:8!==c.nodeType&&(b+=this.getText(c.childNodes));return b};
GeoXml.prototype.processXML=function(a,b,c){var d=[];"undefined"!=typeof b&&(d="string"==typeof b?b.split(","):b);this.docs="array"==typeof a?a:[a];this.progress+=this.docs.length;for(a=0;a<this.docs.length;a++)this.mb.showMess("Processing "+d[a]),this.processing(this.docs[a],d[a],c)};
GeoXml.prototype.makeDescription=function(a,b,c){for(var d="",f=a.childNodes.length,e=0,g;f--;){var h=a.childNodes.item(e),k=h.nodeName;g=k.split(":");var l="",l=1<g.length?g[1]:k;if(l.match(/^(lat|long|visible|visibility|boundedBy|StyleMap|drawOrder|styleUrl|posList|coordinates|Style|Polygon|LineString|Point|LookAt|drawOrder|Envelope|Box|MultiPolygon|where|guid)/))this.currdeschead="";else if(l.match(/#text|the_geom|SchemaData|ExtendedData|#cdata-section/)||l.match(/Snippet/i)||(l.match(/SimpleData/)&&
(l=h.getAttribute("name")),this.currdeschead="<b>&nbsp;"+l+"&nbsp;</b> :"),g=h.nodeValue,"link"==k&&((k=h.getAttribute("href"))&&"null"!=k?g='<a target="_blank" title="'+k+'" href="'+k+'">Link</a>':g&&"null"!=g&&(g='<a target="_blank" title="'+g+'" href="'+g+'">Link</a>'),this.currdeschead="Link to Article"),l.match(/(\S)*(name|title)(\S)*/i))g||(g=this.getText(h)),(b=g)&&"undefined"!=typeof b&&b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length),this.currdeschead="";else if(g&&g.match(/(\S)+/)&&
(g.match(/^http:\/\/|^https:\/\//i)?g='<a target="_blank" " href="'+g+'">[go]</a>':b&&""!=b||(b=g)&&"undefined"!=typeof b&&b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length)),g&&"null"!=g&&"  "!=g&&" "!=g&&!0!=g.match(/(\s|\t|\n)*/)&&(""!=this.currdeschead&&(d+="<br />"),d+=this.currdeschead+""+g+"",this.currdeschead=""),h.childNodes.length&&(h=this.makeDescription(h,b,c+1)))d+=h.desc,"undefined"!=typeof h.title&&h.title&&(b=h.title,b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length+
c));e++}a={};a.desc=d;a.title=b;return a};GeoXml.prototype.randomColor=function(){for(var a="#",b=0;6>b;b++)var c=parseInt(16*Math.random(),10)+1,a=a+c.toString(16);return a.substring(0,7)};
GeoXml.prototype.handleGeomark=function(a,b,c){var d,f,e=!0;this.hideall&&(e=!1);var g=!0,h=!0,k,l;d=[];var q,r="",s=[],g=q=0,h=[],n,m,D=new google.maps.LatLngBounds,A=a.getElementsByTagName("coordinates");1>A.length&&(A=a.getElementsByTagName("gml:coordinates"));if(1>A.length){A=[];s=a.getElementsByTagName("gml:posList");1>s.length&&(s=a.getElementsByTagName("posList"));for(m=0;m<s.length;m++){r=" ";d=this.getText(s.item(m)).split(" ");if(this.isWFS)for(n=0;n<d.length-1;n++)d[n]&&" "!=d[n]&&!isNaN(parseFloat(d[n]))&&
(r+=""+parseFloat(d[n])+","+parseFloat(d[n+1]),r+=" ",n++);else for(n=0;n<d.length-1;n++)d[n]&&" "!=d[n]&&!isNaN(parseFloat(d[n]))&&(r+=""+parseFloat(d[n+1])+","+parseFloat(d[n]),r+=" ",n++);r&&(s.item(m).parentNode&&"gml:LineString"==s.item(m).parentNode.nodeName?q++:g++,d="<coordinates>"+r+"</coordinates>",d=this.parseXML(d),A.push&&A.push(d))}g=a.getElementsByTagName("gml:pos");1>g.length&&(g=a.getElementsByTagName("gml:pos"));if(g.length)for(r=0;r<g.length;r++)q=this.getText(g.item(r)),d=q.split(" "),
d=this.isWFS?this.parseXML("<coordinates>"+d[0]+","+d[1]+"</coordinates>"):this.parseXML("<coordinates>"+d[1]+","+d[0]+"</coordinates>"),A.push&&A.push(d)}g=q=0;s=this.makeDescription(a,"");d="<div id='currentwindow' style='overflow:auto;height:"+this.iwheight+"px' >"+s.desc+"</div> ";!f&&s.title&&(f=s.title,f.length>this.maxtitlewidth&&(this.maxtitlewidth=f.length));var s=[],v;for(n=0;n<A.length;n++){m=!1;!A[n].parentNode||"gml:Box"!=A[n].parentNode.nodeName&&"gml:Envelope"!=A[n].parentNode.nodeName||
(m=!0);var r=this.getText(A[n]),r=r+" ",r=r.replace(/\s+/g," "),r=r.replace(/^ /,""),r=r.replace(/, /,","),w=r.split(" ");if(1==w.length||""==w[1])v=w[0].split(","),v=new google.maps.LatLng(parseFloat(v[1])/c.ys-c.y,parseFloat(v[0])/c.xs-c.x),this.bounds.extend(v),m||("undefined"==typeof f&&(f=this.unnamedplace),this.opts.createmarker?this.opts.createmarker(v,f,d,0,b,null,e):this.createMarker(v,f,d,0,b,null,e));else{for(r=0;r<w.length-1;r++)v=w[r].split(","),v=new google.maps.LatLng(parseFloat(v[1])/
c.ys-c.y,parseFloat(v[0])/c.xs-c.x),h.push(v),D.extend(v);this.bounds.extend(D.getNorthEast());this.bounds.extend(D.getSouthWest());m||s.push(h)}}if(s&&!(1>s.length)){c=a.getElementsByTagName("LineString");1>c.length&&(c=a.getElementsByTagName("gml:LineString"));if(c.length||0<q)k=this.style.width,c=this.style.color,l=this.style.opacity,"undefined"==typeof f&&(f=this.unnamedpath),this.opts.createpolyline?this.opts.createpolyline(s,c,k,l,D,f,d,b,e):this.createPolyline(s,c,k,l,D,f,d,b,e);c=a.getElementsByTagName("Polygon");
1>c.length&&(c=a.getElementsByTagName("gml:Polygon"));if(c.length||0<g)a=this.randomColor(),c=this.randomColor(),h=g=1,"undefined"==typeof f&&(f=this.unnamedarea),this.opts.createpolygon?this.opts.createpolygon(s,c,k,l,a,void 0,D,f,d,b,e,g,h):this.createPolygon(s,c,k,l,a,void 0,D,f,d,b,e,g,h)}};
GeoXml.prototype.handlePlacemark=function(a,b,c,d){var f=a.getElementsByTagName("MultiGeometry");if(1>f.length)this.handlePlacemarkGeometry(a,a,b,c,d);else{var e,g=f[0].getElementsByTagName("Point");for(e=0;e<g.length;e++)this.handlePlacemarkGeometry(a,g[e],b,c,d);g=f[0].getElementsByTagName("LineString");for(e=0;e<g.length;e++)this.handlePlacemarkGeometry(a,g[e],b,c,d);f=f[0].getElementsByTagName("Polygon");for(e=0;e<f.length;e++)this.handlePlacemarkGeometry(a,f[e],b,c,d)}};
GeoXml.prototype.handlePlacemarkGeometry=function(a,b,c,d,f){var e,g,h,k;e=g="";var l=0,q,r,s=!0;this.hideall&&(s=!1);var n=!1,m,D,A,v,w,C,y,I,J=[],E=[],t=[],u,p,z,B,K=a.getAttribute("id"),M=B=J=0,L=t="",N="";z=a.getAttribute("lat");"undefined"!=typeof z&&(q=z);z=a.getAttribute("lon");"undefined"!=typeof z&&(n=!0,r=z);var H=b.getElementsByTagName("coordinates");1>H.length&&(H=b.getElementsByTagName("gml:coordinates"));if(1>H.length){var H=[],F=b.getElementsByTagName("gml:posList");F.length||(F=b.getElementsByTagName("posList"));
for(z=0;z<F.length;z++){t=" ";u=this.getText(F.item(z))+" ";u=u.replace(/(\s)+/g," ");u=u.split(" ");if(this.isWFS)for(p=0;p<u.length-1;p++)isNaN(parseFloat(u[p]))||isNaN(parseFloat(u[p+1]))||(t+=""+parseFloat(u[p])+","+parseFloat(u[p+1]),t+=" ",p++);else for(p=0;p<u.length-1;p++)isNaN(parseFloat(u[p]))||isNaN(parseFloat(u[p+1]))||(t+=""+parseFloat(u[p+1])+","+parseFloat(u[p]),t+=" ",p++);t&&(F.item(z).parentNode&&"gml:LineString"==F.item(z).parentNode.nodeName?B++:M++,t="<coordinates>"+t+"</coordinates>",
p=this.parseXML(t),H.push&&H.push(p))}z=b.getElementsByTagName("gml:pos");1>z.length&&(z=b.getElementsByTagName("gml:pos"));if(z.length)for(b=0;b<z.length;b++)t=this.getText(z.item(b))+" ",u=t.split(" "),p=this.isWFS?this.parseXML("<coordinates>"+u[0]+","+u[1]+"</coordinates>"):this.parseXML("<coordinates>"+u[1]+","+u[0]+"</coordinates>"),H.push&&H.push(p)}for(b=0;b<a.childNodes.length;b++){u=a.childNodes.item(b).nodeName;t=this.getText(a.childNodes.item(b));p=u.split(":");u=!1;switch(1<p.length?
p[1].toLowerCase():p[0].toLowerCase()){case "name":h=t;h.length+d>this.maxtitlewidth&&(this.maxtitlewidth=h.length+d);break;case "title":g=t;g.length+d>this.maxtitlewidth&&(this.maxtitlewidth=g.length+d);break;case "desc":case "description":(e=GeoXml.getDescription(a.childNodes.item(b)))||(e=t);if(p=e.match(/src=\"(.*)\"/i))for(z=1;z<p.length;z++)p[z].match(/^http/)||(B=(this.url.match(/^http/),this.url.lastIndexOf("/")),-1!=B&&(newsrc=this.url.substring(0,B)+"/"+p[z],e=e.replace(p[z],newsrc)));this.opts.preloadHTML&&
e&&e.match(/<(\s)*img/i)&&(p=document.createElement("span"),p.style.visibility="visible",p.style.position="absolute",p.style.left="-1200px",p.style.top="-1200px",p.style.zIndex=this.overlayman.markers.length,document.body.appendChild(p),p.innerHTML=e);if(e.match(/^http:\/\//i))if(p=e.split(/(\s)+/),1<p.length)for(e='<a href="'+p[0]+'">'+p[0]+"</a>",z=1;z<p.length;z++)e+=p[z];else e='<a href="'+e+'">'+e+"</a>";break;case "visibility":"0"==t&&(s=!1);break;case "Snippet":case "snippet":N=t;break;case "href":case "link":if(t)e+=
"<p><a target='_blank' href='"+t+"'>link</a></p>",L=t;else if(p=a.childNodes.item(b).getAttribute("href"))(L=a.childNodes.item(b).getAttribute("type"))&&L.match(/image/)&&(e+='<img style="width:256px" src=\''+p+"' />"),L=p;break;case "author":e+="<p><b>author:</b>"+t+"</p>";break;case "time":e+="<p><b>time:</b>"+t+"</p>";break;case "lat":q=t;break;case "long":r=t;n=!0;break;case "box":J++;u=!0;break;case "styleurl":l=t;k=this.styles[l];break;case "stylemap":M=!1;p=a.childNodes.item(b);for(z=0;z<p.childNodes.length&&
!M;z++)for(F=p.childNodes[z],B=0;B<F.childNodes.length&&!M;B++)"Style"==F.childNodes[B].nodeName&&(k=this.handleStyle(F.childNodes[B],null,k),M=!0);break;case "Style":case "style":l=null,k=this.handleStyle(a.childNodes.item(b),null,k)}if(u){u=t.split(" ");t="";for(p=0;p<u.length-1;p++)isNaN(parseFloat(u[p]))||isNaN(parseFloat(u[p+1]))||(t+=""+parseFloat(u[p+1])+","+parseFloat(u[p]),t+=" ",p++);""!=t&&(p=this.parseXML("<coordinates>"+t+"</coordinates>"),H.push&&H.push(p))}}!h&&g&&(h=g);f&&(alert("overriding style with"+
f.url),k=f);var O;0!=this.iwheight&&(O="height:"+this.iwheight+"px");"undefined"==typeof e||!e||this.opts.makedescription?(a=this.makeDescription(a,""),e="<div id='currentpopup' style='overflow:auto;"+O+"' >"+a.desc+"</div> ",!h&&a.title&&(h=a.title,h.length+d>this.maxtitlewidth&&(this.maxtitlewidth=h.length+d))):this.iwheight&&(e="<div id='currentpopup' style='overflow:auto;"+O+"' >"+e+"</div> ");n&&"undefined"!=typeof q&&q&&(p=this.parseXML("<coordinates>"+(""+r+","+q+" ")+"</coordinates>"),H.push(p));
for(d=0;d<H.length;d++)if(q=!1,H[d].parentNode&&H[d].parentNode.nodeName.match(/^(gml:Box|gml:Envelope)/i)&&(q=!0),t=this.getText(H[d]),t+=" ",t=t.replace(/(\s)+/g," "),t=t.replace(/^ /,""),t=t.replace(/, /,","),r=t.split(" "),1==r.length||""==r[1])t=r[0].split(","),n=new google.maps.LatLng(parseFloat(t[1]),parseFloat(t[0])),this.overlayman.folderBounds[c].extend(n),q||("undefined"==typeof h&&(h=this.unnamedplace),this.opts.createmarker?this.opts.createmarker(n,h,e,l,c,k,s,K,L,N):this.createMarker(n,
h,e,l,c,k,s,K,L,N));else{J=[];y=new google.maps.LatLngBounds;for(b=0;b<r.length-1;b++)t=r[b].split(","),n=new google.maps.LatLng(parseFloat(t[1]),parseFloat(t[0])),J.push(n),y.extend(n);this.overlayman.folderBounds[c].extend(y.getSouthWest());this.overlayman.folderBounds[c].extend(y.getNorthEast());this.bounds.extend(y.getSouthWest());this.bounds.extend(y.getNorthEast());q||E.push(J)}if(E&&!(1>E.length)){u=H[0].parentNode.nodeName;if(u.match(/^(LineString)/i)||u.match(/^(gml:LineString)/i))k?(C=k.strokeWeight,
w=k.strokeColor,D=k.strokeOpacity):(C=this.style.width,w=this.style.color,D=this.style.opacity),"undefined"==typeof h&&(h=unnamedpath),this.opts.createpolyline?this.opts.createpolyline(E,w,C,D,y,h,e,c,s,K):this.createPolyline(E,w,C,D,y,h,e,c,s,K);if(u.match(/^(LinearRing)/i)||u.match(/^(gml:LinearRing)/i))k&&(C=k.strokeWeight,w=k.strokeColor,D=k.strokeOpacity,v=k.fillOpacity,A=k.fillColor,I=k.fill,m=k.outline),"undefined"==typeof I&&(I=0),"undefined"==typeof w&&(w=this.style.color),"undefined"==typeof A&&
(A=this.randomColor()),"undefined"==typeof h&&(h=this.unnamedarea),this.opts.createpolygon?this.opts.createpolygon(E,w,C,D,A,v,y,h,e,c,s,I,m,K):this.createPolygon(E,w,C,D,A,v,y,h,e,c,s,I,m,K)}};
GeoXml.prototype.makeIcon=function(a,b,c,d){var f=1,e,g=0.5,h=0.5;if(d){var g=d.getAttribute("xunits"),k=d.getAttribute("x"),l=32,h=32;this.opts.baseicon&&(l=this.opts.baseicon.size.width,h=this.opts.baseicon.size.height);g="fraction"==g?parseFloat(k):parseFloat(k)/l;k=d.getAttribute("yunits");d=d.getAttribute("y");h="fraction"==k?1-parseFloat(d):1-parseFloat(d)/h}"number"==typeof c&&(f=c);b||(a?a.url&&(b=a.url,f=a.scale):(b="http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png",e=new google.maps.MarkerImage(b,
new google.maps.Size(16*f,16*f)),e.origin=new google.maps.Point(0*f,0*f),e.anchor=new google.maps.Point(16*f*g,16*f*h)));b&&(this.opts.baseicon?(a=this.opts.baseicon,e=new google.maps.MarkerImage(b,this.opts.baseicon.size),e.origin=this.opts.baseicon.origin,e.anchor=new google.maps.Point(this.opts.baseicon.size.width*f*g,this.opts.baseicon.size.height*f*h),e.scaledSize=this.opts.baseicon.scaledSize?this.opts.baseicon.scaledSize:new google.maps.Size(a.size.width*f,a.size.height*f),e.url=b):(e=new google.maps.MarkerImage(b,
new google.maps.Size(32,32),new google.maps.Point(0,0),new google.maps.Point(32*f*g,32*f*h),new google.maps.Size(32*f,32*f)),this.opts.printgif&&(f=b.split("/"),f=f[f.length-1],f=this.opts.printgifpath+f.replace(/.png/i,".gif"),e.printImage=f,e.mozPrintImage=f),this.opts.noshadow?e.shadow="":-1<b.indexOf("/red.png")||-1<b.indexOf("/blue.png")||-1<b.indexOf("/green.png")||-1<b.indexOf("/yellow.png")||-1<b.indexOf("/lightblue.png")||-1<b.indexOf("/purple.png")||-1<b.indexOf("/orange.png")||-1<b.indexOf("/pink.png")||
-1<b.indexOf("-dot.png")?e.shadow="http://maps.google.com/mapfiles/ms/icons/msmarker.shadow.png":-1<b.indexOf("-pushpin.png")||-1<b.indexOf("/pause.png")||-1<b.indexOf("/go.png")||-1<b.indexOf("/stop.png")?e.shadow="http://maps.google.com/mapfiles/ms/icons/pushpin_shadow.png":(b=b.replace(".png",".shadow.png"),b.indexOf(".jpg")&&(b=""),e.shadow=b)));this.opts.noshadow&&(e.shadow="");return e};
GeoXml.prototype.handleStyle=function(a,b,c){var d=a.getElementsByTagName("IconStyle"),f,e,g,h;g=1;h=0;myscale=1;var k="#";b&&(k="#"+b);0<d.length&&(b=this.getText(d[0].getElementsByTagName("href")[0]),b||(b=c.url),(f=parseFloat(this.getText(d[0].getElementsByTagName("scale")[0]),10))&&(myscale=f),d=d[0].getElementsByTagName("hotSpot"),c=this.makeIcon(c,b,myscale,d[0]),c.scale=myscale,this.styles[k]=c);c=a.getElementsByTagName("LineStyle");0<c.length&&(d=parseInt(this.getText(c[0].getElementsByTagName("width")[0]),
10),1>d&&(d=1),c=this.getText(c[0].getElementsByTagName("color")[0]),b=c.substr(0,2),f=c.substr(2,2),e=c.substr(4,2),c=c.substr(6,2),c="#"+c+e+f,b=parseInt(b,16)/256,this.opts.overrideOpacity&&(b=this.opts.overrideOpacity),this.styles[k]||(this.styles[k]={},1),this.styles[k].strokeColor=c,this.styles[k].strokeWeight=d,this.styles[k].strokeOpacity=b);d=a.getElementsByTagName("PolyStyle");0<d.length&&(c=this.getText(d[0].getElementsByTagName("color")[0]),a=this.getText(d[0].getElementsByTagName("colorMode")[0]),
0!=d[0].getElementsByTagName("fill").length&&(g=parseInt(this.getText(d[0].getElementsByTagName("fill")[0]),10)),0!=d[0].getElementsByTagName("outline").length&&(h=parseInt(this.getText(d[0].getElementsByTagName("outline")[0]),10)),b=c.substr(0,2),f=c.substr(2,2),e=c.substr(4,2),c=c.substr(6,2),c="#"+c+e+f,b=parseInt(b,16)/256,this.opts.overrideOpacity&&(b=this.opts.overrideOpacity),this.styles[k]||(this.styles[k]={}),this.styles[k].fill=g,this.styles[k].outline=h,"random"!=a?this.styles[k].fillColor=
c:this.styles[k].colortint=c,this.styles[k].fillOpacity=b,g||(this.styles[k].fillOpacity=0),h||(this.styles[k].strokeOpacity=0));return c=this.styles[k]};
GeoXml.prototype.processKML=function(a,b,c,d,f,e){var g=this.map,h,k=this.forcefoldersopen;"kml"==a.nodeName&&(h=this.docicon);"Document"==a.nodeName&&(h=this.kmlicon);"Folder"==a.nodeName&&(h=this.foldericon);var l=[],q=[],r=[],s="",n="",m=!1;this.hideall||(m=!0);var D=!1,A=!1,v,w=null,C=1,y,I=!1,J=!1,E=[],t=[],u,p,z;a.getAttribute("id");for(var B=0;B<a.childNodes.length;B++)switch(u=a.childNodes.item(B),p=u.nodeName,p){case "name":case "title":c=this.getText(u);c.length+f>this.maxtitlewidth&&(this.maxtitlewidth=
c.length+f);break;case "Folder":case "Document":q.push(u);break;case "GroundOverlay":v=this.getText(u.getElementsByTagName("href")[0]);var K=parseFloat(this.getText(u.getElementsByTagName("north")[0])),M=parseFloat(this.getText(u.getElementsByTagName("south")[0])),L=parseFloat(this.getText(u.getElementsByTagName("east")[0])),N=parseFloat(this.getText(u.getElementsByTagName("west")[0])),H=this.getText(u.getElementsByTagName("attribution")[0]);p=new google.maps.LatLng(M,N);y=new google.maps.LatLng(K,
L);this.bounds.extend(p);this.bounds.extend(y);C=this.getText(u.getElementsByTagName("color")[0]);C=parseInt(C.substring(1,3),16)/256;u=this.getText(u.getElementsByTagName("name")[0]);if(v.match(/arcimsproxy/i)){if(v+="&bbox="+N+","+M+","+L+","+K+"&response=img",y=new google.maps.LatLngBounds(p,y),I=!0,p=this.makeWMSTileLayer(v,m,u,C,H,c,y))p.bounds=y,p.title=u,p.opacity=C,p.visible=m,p.url=v,this.quiet||this.mb.showMess("Adding Tiled ArcIms Overlay "+c,1E3),E.push(p)}else if(v.match(/request=getmap/i)){if(v+=
"&bbox="+N+","+M+","+L+","+K,y=new google.maps.LatLngBounds(p,y),I=!0,p=this.makeWMSTileLayer(v,m,u,C,H,c,y))p.bounds=y,p.title=u,p.opacity=C,p.visible=m,p.url=v,this.quiet||this.mb.showMess("Adding Tiled WMS Overlay "+c,1E3),E.push(p)}else y=new google.maps.LatLngBounds(p,y),w=new google.maps.GroundOverlay(v,y),w.url=v,w.title=u,w.visible=m,w.bounds=y,w.getBounds=function(){return this.bounds},J=D=!0,this.quiet||this.mb.showMess("Adding GroundOverlay "+c,1E3),t.push(w);break;case "NetworkLink":r.push(this.getText(u.getElementsByTagName("href")[0]));
A=!0;break;case "description":case "Description":s=GeoXml.getDescription(u);break;case "open":"1"==this.getText(u)&&(k=!0);"0"==this.getText(u)&&(k=this.forcefoldersopen);break;case "visibility":"0"==this.getText(u)&&(m=!1);break;case "snippet":case "Snippet":n=GeoXml.stripHTML(this.getText(u));n=n.replace(/\n/g,"");break;default:for(C=0;C<b.length;C++)p==b[C]&&l.push(u)}B=this.overlayman.folders.length;1<q.length||l.length||w||I?(this.overlayman.folders.push([]),this.overlayman.subfolders.push([]),
this.overlayman.folderhtml.push([]),this.overlayman.folderhtmlast.push(0),this.overlayman.folderBounds.push(new google.maps.LatLngBounds),this.kml.push(new KMLObj(c,s,!1,B)),e=this.kml.length-1,h=this.createFolder(B,c,d,h,s,n,!0,m)):h=d;if("Folder"==a.nodeName||"Document"==a.nodeName)this.kml[e].open=k,this.kml[e].folderid=h;if(w||I)this.kml[this.kml.length-1].visibility=m,this.kml[this.kml.length-1].groundOverlays.push({url:v,bounds:y});if(A)for(a=/&amp;/g,x=0;x<r.length;x++)v=r[x],v=v.replace(a,
"&"),v=v.replace(/\n/g,""),c=c.replace(/'/g,"&#39;"),this.progress++,top.standalone||"undefined"!=typeof this.proxy&&(v=this.proxy+escape(v)),setTimeout(this.myvar+".loadXMLUrl('"+v+"','"+c+"',null,null,'"+d+"');",1E3);if(I&&E.length)for(d=0;d<E.length;d++)p=E[d],r="",this.basesidebar&&(z=this.overlayman.markers.length,this.nolegend||(r=p.url.replace(/height=(\d)+/i,"height=100"),r=r.replace(/width=(\d)+/i,"width=100"),r='<img src="'+r+'" style="width:100px" />')),this.sidebarsnippet&&""==n&&(n=GeoXml.stripHTML(s),
desc2=desc2.substring(0,40)),parm=this.myvar+"$$$"+p.title+"$$$tiledoverlay$$$"+z+"$$$"+r+"$$$"+p.visible+"$$$"+(this.baseLayers.length-1)+"$$$"+n,g=this.map,google.maps.event.addListener(p,"zoomto",function(){g.fitBounds(this.getBounds())}),this.overlayman.AddMarker(p,c,B,parm,!0,!0);if(J&&t.length)for(var F=0;F<t.length;F++)this.basesidebar&&(z=this.overlayman.markers.length,r='<span style="background-color:black;border:2px solid brown;">&nbsp;&nbsp;&nbsp;&nbsp;</span> ',this.sidebarsnippet&&""==
n&&(n=GeoXml.stripHTML(s),desc2=desc2.substring(0,40)),parm=this.myvar+"$$$"+t[F].title+"$$$polygon$$$"+z+"$$$"+r+"$$$"+t[F].visible+"$$$null$$$"+n,g=this.map,google.maps.event.addListener(t[F],"zoomto",function(){g.fitBounds(t[F].getBounds())}),this.overlayman.folderBounds[B].extend(t[F].getBounds().getSouthWest()),this.overlayman.folderBounds[B].extend(t[F].getBounds().getNorthEast()),D=!0,this.overlayman.AddMarker(t[F],c,B,parm,m)),t[F].setMap(this.map);for(s=0;s<l.length;s++)this.handlePlacemark(l[s],
B,f+1);for(s=n=0;s<q.length;s++)m=this.processKML(q[s],b,c,h,f+1,e),"number"==typeof m&&m!=B&&(this.overlayman.folderBounds[m]?(p=this.overlayman.folderBounds[m].getSouthWest(),y=this.overlayman.folderBounds[m].getNorthEast(),this.overlayman.folderBounds[B].extend(p),this.overlayman.folderBounds[B].extend(y)):this.overlayman.folderBounds[m]=new google.maps.LatLngBounds,this.overlayman.subfolders[B].push(m),m!=B&&this.kml[B].folders.push(m),n++);if(n||l.length||D)this.bounds.extend(this.overlayman.folderBounds[B].getSouthWest()),
this.bounds.extend(this.overlayman.folderBounds[B].getNorthEast());0!=q.length||0!=l.length||this.opts.basesidebar||this.ParseURL();return B};
GeoXml.prototype.processGPX=function(a,b,c,d){var f;"gpx"==a.nodeName&&(f=this.gmlicon);if("rte"==a.nodeName||"trk"==a.nodeName||"trkseg"==a.nodeName)f=this.foldericon;for(var e=[],g=[],h="",k,l,q=this.forcefoldersopen,r="",s=0;s<a.childNodes.length;s++){var n=a.childNodes.item(s),m=n.nodeName;if("name"==m||"title"==m)b=this.getText(n),b.length+d>this.maxtitlewidth&&(this.maxtitlewidth=b.length+d);"rte"==m&&g.push(n);"trk"==m&&g.push(n);"trkseg"==m&&g.push(n);"trkpt"==m&&(e.push(n),k=n.getAttribute("lat"),
"undefined"!=typeof k&&(l=k),k=n.getAttribute("lon"),"undefined"!=typeof k&&(r+=k+","+l+" "));"rtept"==m&&(e.push(n),k=n.getAttribute("lat"),"undefined"!=typeof k&&(l=k),k=n.getAttribute("lon"),"undefined"!=typeof k&&(r+=k+","+l+" "));"wpt"==m&&e.push(n);if("description"==m||"desc"==m)h=this.getText(n)}r.length&&(l=this.parseXML('<?xml version="1.0"?><Placemark><name>'+b+"</name><description>"+h+"</description><LineString><coordinates>"+r+"</coordinates></LineString></Placemark>").documentElement,
e.push(l));l=this.overlayman.folders.length;if(e.length||"gpx"==a.nodeName)this.overlayman.folders.push([]),this.overlayman.subfolders.push([]),this.overlayman.folderhtml.push([]),this.overlayman.folderhtmlast.push(0),this.overlayman.folderBounds.push(new google.maps.LatLngBounds),this.kml.push(new KMLObj(b,h,q,l)),c=this.createFolder(l,b,c,f,h,"",!0,!0);for(a=0;a<e.length;a++)this.handlePlacemark(e[a],l,d+1);for(a=0;a<g.length;a++)e=this.processGPX(g[a],b,c,d+1),this.overlayman.subfolders[l].push(e),
this.overlayman.folderBounds[l].extend(this.overlayman.folderBounds[e].getSouthWest()),this.overlayman.folderBounds[l].extend(this.overlayman.folderBounds[e].getNorthEast());this.overlayman.folderBounds[l]&&(this.bounds.extend(this.overlayman.folderBounds[l].getSouthWest()),this.bounds.extend(this.overlayman.folderBounds[l].getNorthEast()));return l};
GeoXml.prototype.ParseURL=function(){for(var a=topwin.location.search.substring(1).split("&"),b=this.overlayman.markers,c=0;c<a.length;c++){var d=a[c].indexOf("="),f=a[c].substring(0,d).toLowerCase(),d=unescape(a[c].substring(d+1)),e=0;if(d)switch(f){case "openbyid":for(e=0;e<b.length;e++)if(f=b[e].id,f==d){this.overlayman.markers[e].setMap(this.map);this.overlayman.markers[e].hidden=!1;google.maps.event.trigger(this.overlayman.markers[e],"click");break}break;case "kml":case "url":case "src":case "geoxml":this.urls.push(d);
this.parse();break;case "openbyname":for(e=0;e<b.length;e++)if(f=b[e].title,f==d){this.overlayman.markers[e].setMap(this.map);this.overlayman.markers[e].hidden=!1;google.maps.event.trigger(this.overlayman.markers[e],"click");break}}}};
GeoXml.prototype.processing=function(a,b,c,d,f){this.overlayman.miStart=new Date;d||(d=b);f||(f=0);var e;a=a.documentElement;if(!a)return 0;var g=[],g=a.nodeName,h=this.forcefoldersopen;e=g.split(":");1<e.length&&(g=e[1]);this.wfs=!1;"FeatureCollection"==g&&(e=Lance$(this.basesidebar),b||(b=void 0),"undefined"==typeof b&&(b="Un-named GML"),this.isWFS=!0,b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length),e&&(e.style.display=""),e=this.overlayman.folders.length,this.processGML(a,b,c,d,this.kml.length-
1),this.kml[0].folders.push(e));if("gpx"==g){b||(b=void 0);"undefined"==typeof b&&(b="Un-named GPX");this.title=b;b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length);if(e=Lance$(this.basesidebar))e.style.display="";e=this.overlayman.folders.length;this.processGPX(a,b,this.basesidebar,f);this.kml[0].folders.push(e)}else if("kml"==g){f=a.getElementsByTagName("Style");for(d=0;d<f.length;d++)(e=f[d].getAttribute("id"))&&this.handleStyle(f[d],e);f=a.getElementsByTagName("StyleMap");for(d=0;d<f.length;d++)if(e=
f[d].getAttribute("id"))for(var k=!1,h=f[d],g=0;g<h.childNodes.length&&!k;g++){c=h.childNodes[g];for(var l=0;l<c.childNodes.length&&!k;l++){var q=c.childNodes[l].nodeName;"styleUrl"==q&&(k=this.getText(c.childNodes[l]),this.styles["#"+e]=this.styles[k],k=!0);"Style"==q&&(this.handleStyle(c.childNodes[l],e),k=!0)}}b||(b=void 0);"undefined"==typeof b&&(b="KML Document");this.title=b;b.length>this.maxtitlewidth&&(this.maxtitlewidth=b.length);f=["Placemark"];e=a.getElementsByTagName("Schema");for(h=0;h<
e.length;h++)d=e[h].getAttribute("parent"),"Placemark"==d&&(d=e[h].getAttribute("name"),f.push(d));if(e=Lance$(this.basesidebar))e.style.display="";e=this.overlayman.folders.length;d=this.kml.length-1;this.processKML(a,f,b,this.basesidebar,e,d);this.kml[d].folders.push(e)}else if(g=a.getElementsByTagName("item"),1>g.length&&(g=a.getElementsByTagName("atom")),1>g.length&&(g=a.getElementsByTagName("entry")),b||(b=void 0),"undefined"==typeof b&&(b="News Feed"),this.title=b,b.length>this.maxtitlewidth&&
(this.maxtitlewidth=b.length),this.opts.baseicon?a=this.opts.baseicon:(a=new google.maps.MarkerImage(this.rssicon,new google.maps.Size(32,32)),a.origin=new google.maps.Point(0,0),a.anchor=new google.maps.Point(16,32),a.url=this.rssicon),e=this.rssicon.replace(".png",".shadow.png"),a.shadow=e+"_shadow.png",a.strokeColor="#00FFFF",a.strokeWeight="3",a.strokeOpacity=0.5,d||(d="RSS feed"),this.kml[0].folders.push(this.overlayman.folders.length),g.length){if(e=Lance$(this.basesidebar))e.style.display=
"";this.overlayman.folders.push([]);this.overlayman.folderhtml.push([]);this.overlayman.folderhtmlast.push(0);this.overlayman.folderBounds.push(new google.maps.LatLngBounds);e=this.overlayman.folders.length-1;this.kml.push(new KMLObj(b,d,h,e));this.kml[this.kml.length-1].open=h;this.basesidebar&&(c=!0,this.hideall&&(c=!1),this.createFolder(e,b,this.basesidebar,this.globalicon,d,null,h,c));for(d=0;d<g.length;d++)this.handlePlacemark(g[d],e,f,a)}this.progress--;0==this.progress&&(google.maps.event.trigger(this,
"initialized"),this.opts.sidebarid||this.mb.showMess("Finished Parsing",1E3),this.opts.nozoom||this.basesidebar||this.map.fitBounds(this.bounds))};
GeoXml.prototype.createFolder=function(a,b,c,d,f,e,g,h){c=Lance$(c);g=!0;var k=this.myvar+"_folder"+a,l="";h&&(l=" checked ");this.overlayman.folderhtml[k]="";h="display:block";var q="font-weight:normal";"undefined"!=typeof g&&g||(h="display:none",q="font-weight:bold");f&&""!=f||(f=b);f=escape(f);g='<ul><input type="checkbox" id="'+this.myvar+""+a+'FCB" style="vertical-align:middle" ';g=g+l+('onclick="'+this.myvar+".toggleContents("+a+',this.checked)">');g+='&nbsp;<span title="'+e+'" id="'+this.myvar+
"TB"+a+'" oncontextmenu="'+this.myvar+".saveJSON("+a+');" onclick="'+this.myvar+".toggleFolder("+a+')" style="'+q+'">';g+='<img id="'+this.myvar+"FB"+a+'" style="vertical-align:text-top;padding:0;margin:0" height="'+this.sidebariconheight+'" border="0" src="'+d+'" /></span>&nbsp;';g+='<a href="#" onclick="'+this.myvar+".overlayman.zoomToFolder("+a+");"+this.myvar+".mb.showMess('"+f+"',3000);return false;\">"+b+'</a><br><div id="'+k+'" style="'+h+'"></div></ul>';c&&(c.innerHTML+=g);return k};
GeoXml.prototype.processGML=function(a,b,c,d,f){var e=[],g,h=!1,k=0,l=0,q=1,r=1,s,n,m=b,D=!0;this.hideall&&(D=!1);for(var A=this.allfoldersopen,v,w=0;w<a.childNodes.length;w++){var C=a.childNodes.item(w).nodeName,y=a.childNodes.item(w);if("gml:boundedBy"==C||"boundedBy"==C)for(;0<y.childNodes.length;){v=y.childNodes.item(0).nodeName;n=/CRS:84|(4326|4269)$/i;if("Box"==v||"gml:Box"==v){v=y.childNodes.item(0);g=y.childNodes.item(0).getAttribute("srsName");if(g.match(n))h=!0;else for(alert("SRSname ="+
g+"; attempting to create transform"),n=0;n<v.childNodes.length;n++)if(g=v.childNodes.item(n),"gml:coordinates"==g.nodeName||"coordinates"==g.nodeName)q=this.getText(g),q=q.split(" "),l=q[0].split(","),r=q[1].split(","),q=(parseFloat(r[0])-parseFloat(l[0]))/(c.xmax-c.xmin),r=(parseFloat(r[1])-parseFloat(l[1]))/(c.ymax-c.ymin),k=l[0]/q-c.xmin,l=l[1]/r-c.ymin;break}if("Envelope"==v||"gml:Envelope"==v)if(v=y.childNodes.item(0),g=y.childNodes.item(0).getAttribute("srsName"),g.match(n))h=!0;else for(alert("SRSname ="+
g+"; attempting to create transform"),n=0;n<v.childNodes.length;n++)if(g=v.childNodes.item(n),"gml:coordinates"==g.nodeName||"coordinates"==g.nodeName){for(var q=g.split(" "),l=k=1E8,I=-1E8,r=-1E8,J=0;J<q.length-1;J++)s=q[J].split(","),g=parseFloat(s[0]),s=parseFloat(s[1]),g<k&&(k=g),s<l&&(l=s),g>I&&(I=g),s>r&&(r=s);q=(I-k)/(c.xmax-c.xmin);r=(r-l)/(c.ymax-c.ymin);k=k/q-c.xmin;l=l/r-c.ymin}break}"gml:featureMember"!=C&&"featureMember"!=C||e.push(y)}var E;b||(b=m);this.title=b;if(1>e.length)alert("No features found in "+
b),this.mb.showMess("No features found in "+b,3E3);else if(this.mb.showMess("Adding "+e.length+" features found in "+b),this.overlayman.folders.push([]),this.overlayman.folderhtml.push([]),this.overlayman.folderhtmlast.push(0),this.overlayman.folderBounds.push(new google.maps.LatLngBounds),a=this.overlayman.folders.length-1,this.basesidebar&&(E=this.createFolder(a,b,this.basesidebar,this.gmlicon,d,null,A,D)),this.kml.push(new KMLObj(b,d,!0,a)),this.kml[f].open=this.opts.allfoldersopen,this.kml[f].folderid=
E,h)for(b=0;b<e.length;b++)this.handlePlacemark(e[b],a,0);else for(d={xs:q,ys:r,x:k,y:l},b=0;b<e.length;b++)this.handleGeomark(e[b],a,d,0)};google.maps.Polyline.prototype.getBounds=function(){return"undefined"!=typeof this.bounds?this.bounds:this.computeBounds()};google.maps.Polyline.prototype.getPosition=function(){var a=this.getPath();return a.getAt(Math.round(a.getLength()/2))};
google.maps.Polyline.prototype.computeBounds=function(){for(var a=new google.maps.LatLngBounds,b=this.getPath(),c=0;c<b.getLength();c++){var d=b.getAt(c);d&&a.extend(d)}return this.bounds=a};google.maps.Polygon.prototype.getPosition=function(){return this.getBounds().getCenter()};
google.maps.Polygon.prototype.computeBounds=function(){for(var a=new google.maps.LatLngBounds,b=this.getPaths(),c=0;c<b.getLength();c++)for(var d=b.getAt(c),f=0;f<d.getLength();f++){var e=d.getAt(f);e&&a.extend(e)}return this.bounds=a};google.maps.Polygon.prototype.getBounds=function(){return"undefined"!=typeof this.bounds?this.bounds:this.computeBounds()};google.maps.Polygon.prototype.getCenter=function(){return this.getBounds().getCenter()};OverlayManagerView.prototype=new google.maps.OverlayView;
function OverlayManagerView(a){this.setMap(a)}OverlayManagerView.prototype.onAdd=function(){};OverlayManagerView.prototype.draw=function(){};OverlayManagerView.prototype.onRemove=function(){};
OverlayManager=function(a,b){this.myvar=b.myvar;this.paren=b;this.map=a;this.markers=[];this.byid=[];this.byname=[];this.groups=[];this.timeout=null;this.folders=[];this.folderBounds=[];this.folderhtml=[];this.folderhtmlast=[];this.subfolders=[];this.currentZoomLevel=a.getZoom();this.isParsed=!1;this.overlayview=new OverlayManagerView(a);this.maxVisibleMarkers=OverlayManager.defaultMaxVisibleMarkers;this.gridSize=OverlayManager.defaultGridSize;this.minMarkersPerCluster=OverlayManager.defaultMinMarkersPerCluster;
this.maxLinesPerInfoBox=OverlayManager.defaultMaxLinesPerInfoBox;this.icon=OverlayManager.defaultIcon;google.maps.event.addListener(this.paren,"adjusted",OverlayManager.MakeCaller(OverlayManager.Display,this));google.maps.event.addListener(a,"idle",OverlayManager.MakeCaller(OverlayManager.Display,this));google.maps.event.addListener(a,"infowindowclose",OverlayManager.MakeCaller(OverlayManager.PopDown,this));this.icon.pane=this.paren.markerpane};OverlayManager.defaultMaxVisibleMarkers=6E3;
OverlayManager.defaultGridSize=20;OverlayManager.defaultMinMarkersPerCluster=10;OverlayManager.defaultMaxLinesPerInfoBox=15;OverlayManager.defaultIcon=new google.maps.MarkerImage("http://maps.google.com/mapfiles/kml/paddle/blu-circle.png",new google.maps.Size(32,32),new google.maps.Point(0,0),new google.maps.Point(16,12),new google.maps.Size(32,32));OverlayManager.prototype.SetIcon=function(a){this.icon=a};OverlayManager.prototype.SetMaxVisibleMarkers=function(a){this.maxVisibleMarkers=a};
OverlayManager.prototype.SetMinMarkersPerCluster=function(a){this.minMarkersPerCluster=a};OverlayManager.prototype.SetMaxLinesPerInfoBox=function(a){this.maxLinesPerInfoBox=a};
OverlayManager.prototype.AddMarker=function(a,b,c,d,f,e){null!=a.setMap&&a.setMap(this.map);a.hidden=!1;!0!=f&&(a.hidden=!0);this.paren.hideall&&(a.hidden=!0);a.title=b;this.folders[c].push(this.markers.length);b=this.map.getBounds();f=!1;if(b)if("undefined"==typeof a.getBounds)b.contains(a.getPosition())&&(f=!0);else{var g=a.getBounds();g.isEmpty()||b.intersects(g)&&(f=!0)}else f=!0;e&&(f=!0);this.markers.push(a);f&&(a.hidden?(a.setMap(null),a.onMap=!1,a.label&&a.label.hide()):(a.setMap(this.map),
a.onMap=!0));this.DisplayLater();d&&this.folderhtml[c].push(d)};OverlayManager.prototype.zoomToFolder=function(a){this.map.fitBounds(this.folderBounds[a])};
OverlayManager.prototype.RemoveMarker=function(a){for(var b=0;b<this.markers.length;++b)if(this.markers[b]==a){a.onMap&&a.setMap(null);a.label&&a.label.setMap(null);for(var c=0;c<this.groups.length;++c){var d=this.groups[c];if(null!=d){for(var f=0;f<d.markers.length;++f)if(d.markers[f]==a){d.markers[f]=null;--d.markerCount;break}0==d.markerCount?(this.ClearGroup(d),this.groups[c]=null):d==this.poppedUpCluster&&OverlayManager.RePop(this)}}this.markers[b]=null;break}this.DisplayLater()};
OverlayManager.prototype.DisplayLater=function(){null!=this.timeout&&clearTimeout(this.timeout);this.timeout=setTimeout(OverlayManager.MakeCaller(OverlayManager.Display,this),50)};
OverlayManager.Display=function(a){var b,c,d,f,e,g;clearTimeout(a.timeout);if(!a.paren.allRemoved){var h=!1;e=0;if(a.paren.basesidebar)for(d=0;d<a.folderhtml.length;d++){var k=a.folderhtml[d].length;g=a.folderhtmlast[d];if(g<k&&(b=Lance$(a.paren.myvar+"_folder"+d))){a.paren.opts.sortbyname?(e=b.innerHTML,h=a.folderhtml[d].sort(),g=0):(e=b.innerHTML,h=a.folderhtml[d]);for(;g<k;g++)c=h[g].split("$$$",8),e+=a.paren.sidebarfn(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]);a.folderhtmlast[d]=k;b.innerHTML=e;
a.paren.forcefoldersopen&&(b.style.display="block");h=!0;e=k}}h&&0<e&&0==a.paren.progress&&(a.paren.setFolders(),google.maps.event.trigger(a.paren,"parsed"),a.paren.opts.sidebarid||a.paren.mb.showMess("Finished Parsing",1E3),a.paren.mb.showMess("Loaded "+e+"  GeoXML elements in "+((new Date-a.miStart)/1E3+" seconds"),5E3),a.paren.ParseURL(),a.paren.opts.nozoom||a.paren.map.fitBounds(a.paren.bounds));h&&"undefined"!=typeof resizeKML&&resizeKML();var l;d=a.map.getZoom();if(d!=a.currentZoomLevel){for(b=
0;b<a.groups.length;++b)null!=a.groups[b]&&(a.ClearGroup(a.groups[b]),a.groups[b]=null);a.groups.length=0;a.currentZoomLevel=d}a.map.getBounds()&&(l=a.getMapBounds(a),d=l.getSouthWest(),k=l.getNorthEast(),b=k.lng()-d.lng(),e=k.lat()-d.lat(),300>b&&150>e&&(b*=0.05,e*=0.05,l=new google.maps.LatLngBounds(new google.maps.LatLng(d.lat()-e,d.lng()-b),new google.maps.LatLng(k.lat()+e,k.lng()+b))));if(!l&&a.map&&(l=a.getMapBounds(a),!l))return;d=[];e=[];for(b=k=0;b<a.markers.length;++b)if(f=a.markers[b],
g=!1,null!==f){c=a.paren.myvar+"sb"+b;if("undefined"==typeof f.getBounds){var q=f.getPosition();l.contains(q)&&(g=!0,k++)}else q=f.getBounds(),l.intersects(q)&&(g=!0);Lance$(c)&&(g?Lance$(c).className="inView":Lance$(c).className="outView");g&&!1==f.hidden?d.push(b):e.push(b)}for(b=0;b<e.length;++b)f=a.markers[e[b]],f.onMap&&(f.label&&f.label.setMap(null),f.setMap(null),f.onMap=!1);for(b=0;b<a.groups.length;++b)e=a.groups[b],null!=e&&e.marker&&(g=!1,"undefined"==typeof e.marker.getBounds?l.contains(e.marker.getPosition())&&
(g=!0):g=!0,!g&&e.onMap&&(e.marker.setMap(null),e.onMap=!1));if(k>a.maxVisibleMarkers){h||a.paren.mb.showMess("Clustering on "+k+"  GeoXML elements");b=(l.getNorthEast().lat()-l.getSouthWest().lat())/a.gridSize;g=b/Math.cos((l.getNorthEast().lat()+l.getSouthWest().lat())/2*Math.PI/180);for(c=l.getSouthWest().lat();c<=l.getNorthEast().lat();c+=b)for(q=l.getSouthWest().lng();q<=l.getNorthEast().lng();q+=g)e={},e.overlaymanager=a,e.bounds=new google.maps.LatLngBounds(new google.maps.LatLng(c,q),new google.maps.LatLng(c+
b,q+g)),e.markers=[],e.markerCount=0,e.onMap=!1,e.marker=null,a.groups.push(e);for(b=0;b<d.length;++b)if(f=a.markers[d[b]],null!=f&&!f.inCluster)for(c=0;c<a.groups.length;++c)e=a.groups[c],null!=e&&(g=!1,"undefined"==typeof f.getBounds&&e.bounds.contains(f.getPosition())&&(g=!0),g&&(f.inCluster=!0,a.groups[c].markers.push(f),++a.groups[c].markerCount));for(b=0;b<a.groups.length;++b)null!=a.groups[b]&&a.groups[b].markerCount<a.minMarkersPerCluster&&(a.ClearGroup(a.groups[b]),a.groups[b]=null);for(b=
a.groups.length-1;0<=b&&null==a.groups[b];--b)--a.groups.length;for(b=0;b<a.groups.length;++b)if(e=a.groups[b],null!=e)for(c=0;c<e.markers.length;++c)f=e.markers[c],null!=f&&f.onMap&&(f.setMap(null),f.onMap=!1,f.label&&f.label.hide());for(b=0;b<a.groups.length;++b)if(e=a.groups[b],null!=e&&null==e.marker){for(c=q=g=0;c<e.markers.length;++c)f=e.markers[c],null!=f&&(g+=+f.getPosition().lng(),q+=+f.getPosition().lat());f=new google.maps.LatLng(q/e.markerCount,g/e.markerCount);f=new google.maps.Marker({position:f,
icon:OverlayManager.defaultIcon,title:"Cluster"});e.marker=f;google.maps.event.addListener(f,"click",OverlayManager.MakeCaller(OverlayManager.PopUp,e))}}!h&&k&&!0!=a.paren.quiet&&a.paren.mb.showMess("Showing "+k+"  GeoXML elements",500);for(b=0;b<d.length;++b)f=a.markers[d[b]],null==f||f.onMap||f.inCluster||(null!=f.addedToMap&&f.addedToMap(),f.hidden?(f.setMap(null),f.label&&f.label.setMap(null)):(f.onMap=!0,f.setMap(a.map)));for(b=0;b<a.groups.length;++b)e=a.groups[b],null!=e&&e.marker&&(g=!1,"undefined"!=
typeof f.getPosition?l.contains(e.marker.getPosition())&&(g=!0):l.intersects(e.marker.getBounds())&&(g=!0),!e.onMap&&g&&(e.marker.setMap(a.map),e.onMap=!0));OverlayManager.RePop(a)}};
OverlayManager.PopUp=function(a){for(var b=a.overlaymanager,c='<table style="font-size:10px" width="300">',d=0,f=0;f<a.markers.length;++f){var e=a.markers[f];if(null!=e&&(++d,c+="<tr><td>",c=null!=e.smallImage?c+('<img src="'+e.smallImage+'">'):c+('<img src="'+e.image_+'" width="'+e.width_/2+'" height="'+e.height_/2+'">'),c+="</td><td>"+e.title+"</td></tr>",d==b.maxLinesPerInfoBox-1&&a.markerCount>b.maxLinesPerInfoBox)){c+='<tr><td colspan="2">...and '+(a.markerCount-d)+" more</td></tr>";break}}c+=
"</table>";this.paren.lastMarker.infoWindow.close();c={content:c,pixelOffset:new google.maps.Size(0,2),position:b.marker.getPosition()};this.paren.maxiwwidth&&(c.maxWidth=this.paren.maxiwwidth);b.marker.infoWindow=new google.maps.InfoWindow(c);this.paren.lastMarker=b.marker;this.paren.lastMarker.infoWindow.open(this.paren.map);b.poppedUpCluster=a};
OverlayManager.prototype.getMapBounds=function(a){var b;b=1<a.map.getZoom()?new google.maps.LatLngBounds(a.map.getBounds().getSouthWest(),a.map.getBounds().getNorthEast()):new google.maps.LatLngBounds(new google.maps.LatLng(-85.08136444384544,-178.48388434375),new google.maps.LatLng(85.02070771743472,178.00048865625));var c=a.overlayview.getProjection(),d=new google.maps.LatLng(b.getNorthEast().lat(),b.getNorthEast().lng()),f=new google.maps.LatLng(b.getSouthWest().lat(),b.getSouthWest().lng()),d=
c.fromLatLngToDivPixel(d);d.x+=a.gridSize;d.y-=a.gridSize;f=c.fromLatLngToDivPixel(f);f.x-=a.gridSize;f.y+=a.gridSize;a=c.fromDivPixelToLatLng(d);c=c.fromDivPixelToLatLng(f);b.extend(a);b.extend(c);return b};OverlayManager.RePop=function(a){null!=a.poppedUpCluster&&OverlayManager.PopUp(a.poppedUpCluster)};OverlayManager.PopDown=function(a){a.poppedUpCluster=null};
OverlayManager.prototype.ClearGroup=function(a){var b;for(b=0;b<a.markers.length;++b)null!=a.markers[b]&&(a.markers[b].inCluster=!1,a.markers[b]=null);a.markers.length=0;a.markerCount=0;a==this.poppedUpCluster&&this.map.closeInfoWindow();a.onMap&&(a.marker.setMap(null),a.onMap=!1)};OverlayManager.MakeCaller=function(a,b){return function(){a(b)}};
MessageBox=function(a,b,c,d){this.map=a;this.paren=b;this.myvar=b.myvar+"."+c;this.mb=this.centerMe=this.eraseMess=null;d&&(this.mb=d);this.id=this.myvar+"_message"};MessageBox.prototype.hideMess=function(){this.paren.quiet||(this.mb.style.visiblity="hidden",this.mb.style.left="-1200px",this.mb.style.top="-1200px")};
MessageBox.prototype.centerThis=function(){var a,b;a=this.map.getDiv().offsetWidth/2;b=this.map.getDiv().offsetHeight/2;this.mb||(this.mb=Lance$(this.id));this.centerMe&&clearTimeout(this.centerMe);if(this.mb){var c=this.mb.offsetWidth;c>this.map.getDiv().offsetWidth?(c=parseInt(2*a/3,10),this.mb.style.width=c+"px",this.centerMe=setTimeout(this.myvar+".centerThis()",5)):(this.mb.style.left=a-c/2+"px",this.mb.style.top=b-20-this.mb.offsetHeight/2+"px")}else this.centerMe=setTimeout(this.myvar+".centerThis()",
10)};
MessageBox.prototype.showMess=function(a,b){if(this.paren.quiet)console&&console.log(a);else if(a=unescape(a),this.eraseMess&&clearTimeout(this.eraseMess),this.mb||(this.mb=Lance$(this.id)),this.mb){this.mb.innerHTML="<span>"+a+"</span>";b&&(this.eraseMess=setTimeout(this.myvar+".hideMess();",b));var c=this.map.getDiv(),d=this.mb.offsetHeight/2;this.mb.style.left=parseInt(c.offsetWidth/2-this.mb.offsetWidth/2)+"px";this.mb.style.top=parseInt(c.offsetHeight/2-d)+"px";this.mb.style.width="";this.mb.style.height="";
this.centerMe=setTimeout(this.myvar+".centerThis()",5);this.mb.style.visibility="visible"}else c=document.createElement("div"),c.innerHTML=a,c.id=this.myvar+"_message",c.style.position="absolute",c.style.backgroundColor=this.style.backgroundColor||"silver",c.style.opacity=this.style.opacity||0.8,document.all&&(c.style.filter="alpha(opacity="+parseInt(100*c.style.opacity,10)+")"),c.style.color=this.style.color||"black",c.style.padding=this.style.padding||"6px",c.style.borderWidth=this.style.borderWidth||
"3px",c.style.borderColor=this.style.borderColor||"",c.style.backgroundImage=this.style.backgroundImage||"",c.style.borderStyle=this.style.borderStyle||"outset",c.style.visibility="visible",c.style.left="-1200px",c.style.top="-1200px",this.centerMe=setTimeout(this.myvar+".centerThis()",5),c.style.zIndex=1E3,document.body.appendChild(c)};GeoXml.prototype.loadJSONUrl=function(a,b,c,d,f){var e=this;GDownloadUrl(a,function(a){e.parseJSON(a,b,c,d,f)})};
GeoXml.prototype.loadXMLUrl=function(a,b,c,d,f){var e=this;e.DownloadURL(a,function(a){a=e.parseXML(a);e.processing(a,b,c,d,f)},b)};GeoXml.prototype.upgradeLayer=function(a){for(var b=this.map.getMapTypes(),c=!1,d=0;d<b.length;d++)b[d]==this.baseLayers[a]&&(c=!0,this.map.removeMapType(this.baseLayers[a]));c||this.map.addMapType(this.baseLayers[a])};
GeoXml.prototype.makeWMSTileLayer=function(a,b,c,d,f,e,g){gmapstring=new String(a);a=gmapstring.replace("&amp;","&");c=a.split("?");a=c[0]+"?";a=a.replace(/&request=getmap/i,"");a=a.replace(/&service=wms/i,"");b="-180,-90,180,90";c=c[1].split("&");for(d=0;d<c.length;d++)switch(f=c[d].split("="),f[0].toLowerCase()){case "version":break;case "bbox":b=f[1];break;case "width":case "height":break;case "service":break;case "servicename":break;case "atlasname":break;case "styles":break;case "layers":break;
case "format":break;case "opacity":parseFloat(f[1]);break;case "crs":case "srs":break;case "gmcrs":break;case "queryable":break;case "getmap":break;case "service":break;default:f[0]&&(a+="&"+c[d])}a=b.split(",");parseFloat(a[0]);b=parseFloat(a[1]);parseFloat(a[2]);a=parseFloat(a[3])-b;b=0;for(c=180;c>=a;)c/=2,b++};GeoXml.SEMI_MAJOR_AXIS=6378137;GeoXml.ECCENTRICITY=0.08181919131087181;GeoXml.DEG2RAD=180/Math.PI;GeoXml.merc2Lon=function(a){return a*GeoXml.DEG2RAD*GeoXml.SEMI_MAJOR_AXIS};
GeoXml.merc2Lat=function(a){a*=GeoXml.DEG2RAD;var b=Math.sin(a);return GeoXml.SEMI_MAJOR_AXIS*Math.log(Math.tan((a+Math.PI/2)/2)*Math.pow((1-GeoXml.ECCENTRICITY*b)/(1+GeoXml.ECCENTRICITY*b),GeoXml.ECCENTRICITY/2))};GeoXml.prototype.toggleLabels=function(a){a?this.addLabels():this.removeLabels()};GeoXml.prototype.addLabels=function(){this.labels.onMap=!0;this.labels.setMap(this.map)};GeoXml.prototype.removeLabels=function(){this.labels.onMap=!1;this.labels.setMap(null)};var useLegacyLocalLoad=!0;
GeoXml.prototype.DownloadURL=function(a,b,c){if(a){var d,f=this;!topwin.standalone&&this.proxy&&(a=this.proxy+"url="+escape(a));if((topwin.standalone||useLegacyLocalLoad)&&":"==a.substring(2,3))d=new ActiveXObject("Msxml2.DOMDocument.4.0"),d.validateOnParse=!1,d.async=!0,d.load(a),0!=d.parseError.errorCode?(a=d.parseError,alert("GeoXml file appears incorrect\n"+a.reason+" at line:"+a.line)):b(d.doc);else{var e;e||"undefined"==typeof XMLHttpRequest?"undefined"!=typeof ActiveXObject&&(e=new ActiveXObject("Microsoft.XMLHTTP")):
e=new XMLHttpRequest;var g=a;e.overrideMimeType&&e.overrideMimeType("text/xml");e.open("GET",g,!0);e.onreadystatechange=function(){switch(e.readyState){case 4:f.mb.showMess(c+" received",2E3);if("undefined"!=typeof ActiveXObject)d=new ActiveXObject("Microsoft.XMLDOM"),d.async="false",b(e.responseText);else if(e.responseXML)f.mb.showMess(c+" received",2E3),b(e.responseText);else if(200==e.status){var a=e.responseText,g=a.substring(0,400);"<?xml"==a.substring(0,5)&&-1!=g.indexOf("kml")?(f.mb.showMess(c+
" response received",2E3),b(a.responseText)):f.mb.showMess("File does not appear to be a valid GeoData"+a,6E3)}break;case 3:f.mb.showMess("Receiving "+c+"...",2E3);break;case 2:f.mb.showMess("Waiting for "+c,2E3);break;case 1:f.mb.showMess("Sent request for "+c,2E3)}};try{e.send(null)}catch(h){":"!=a.substring(2,3)||useLegacyLocalLoad||(useLegacyLocalLoad=!0,this.DownloadURL(a))}}}};GeoXml.Label=function(a,b,c,d,f){this.pos=a;this.txt_=b;this.cls_=c;this.map_=d;this.style_=f;this.div_=null;this.setMap(d)};
GeoXml.Label.prototype=new google.maps.OverlayView;GeoXml.Label.prototype.onAdd=function(){var a=document.createElement("DIV");a.innerHTML=this.txt_;this.div_=a;this.div_.style.position="absolute";var b=this.getProjection().fromLatLngToDivPixel(this.pos);this.div_.style.fontSize=this.style_.fontSize;this.div_.style.fontFamily=this.style_.fontFamily;a.style.left=b.x+"px";a.style.top=b.y+"px";this.getPanes().floatPane.appendChild(a)};GeoXml.Label.prototype.getPosition=function(){return this.pos};
GeoXml.Label.prototype.draw=function(){var a=this.getProjection().fromLatLngToDivPixel(this.pos),b=this.div_;b.style.left=a.x+"px";b.style.top=a.y+"px"};GeoXml.Label.prototype.onRemove=function(){this.div_.parentNode.removeChild(this.div_);this.div_=null};GeoXml.Label.prototype.hide=function(){this.div_&&(this.div_.style.visibility="hidden")};GeoXml.Label.prototype.show=function(){this.div_&&(this.div_.style.visibility="visible")};
GeoXml.Label.prototype.toggle=function(){this.div_&&("hidden"==this.div_.style.visibility?this.show():this.hide())};GeoXml.Label.prototype.toggleDOM=function(){this.getMap()?this.setMap(null):this.setMap(this.map_)};

